import { COLORSTR } from "./ColorEnum"
import { BATTLE_ATTR, EQUIP_TYPE } from "./CommonEnum"

export var Language = {
    Common: {
        Confirm: "Xác nhận",
        Wan: "Vạn",
        QianWan: "Chục triệu",
        Yi: "Trăm triệu",
        Reincarnation: "{0} đến {1} sao",
        shengji: "Nâng cấp",
        jiasu: "Tăng tốc",
        add: "Tăng",
        LevelShow: "Lv.{0}",
        NotHasTip: "Không đủ",
        buy_limit: "Đã đạt giới hạn mua",
        refresh_limit: "Không đủ lượt làm mới còn lại",
        use: "Sử dụng",
        buy: "Mua",
        other: "Khác",
        level: "Cấp độ",
        OpenLevel: "Mở ở cấp {0}",
        up_grade: "Tăng bậc",
        up_level: "Nâng cấp",
        active: "Kích hoạt",
        unActive: "Chưa kích hoạt",
        rank: "Xếp hạng",
        basic_attr: "Thuộc tính cơ bản",
        add_attr: "Thuộc tính cộng thêm",
        NoTitle: "Chưa có danh hiệu",
            MainTitle: "Kỹ năng",
            TabSkill: "Kỹ năng chủ động",
            TabTalent: "Thiên phú",
            Learn: "Học",
            LevelUp: "Nâng cấp",
            MaxLevel: "Đã đầy cấp",
            OneKeyLevelUp: "Nâng cấp nhanh",
            Refresh: "Làm mới",
            Unlearned: "Chưa học",
            EmptyViewTips: "Nhấn tab phía trên để xem kỹ năng chủ động hoặc thiên phú, rồi thao tác học/nâng cấp ở bên dưới",
            NoDetail: "Chưa có mô tả chi tiết",
            CurrentLevelLabel: "Cấp hiện tại:",
            TargetLabel: "Mục tiêu:",
            TargetEnemy: "Địch",
            TargetAlly: "Đồng minh",
            TargetUnit: "mục tiêu",
            FeatureLabel: "Đặc tính:",
            BasicAttackDesc: "Đánh thường",
            FlagDodge: "Có thể né",
            FlagCrit: "Có thể bạo kích",
            FlagCombo: "Có thể liên kích",
            FlagLeech: "Có thể hút máu",
            FlagLucky: "Có thể gây choáng",
            FlagCounter: "Có thể phản kích",
        LingQu: "Nhận",
        ChongZhi: "Nạp tiền",
        JiangLiYiLingQu: "Phần thưởng đã nhận",
        WeiDaCheng: "Chưa đạt",
        XianGou: [
            "",
            "",
            "Giới hạn mua hàng ngày: {0}",
            "Giới hạn mua hàng tuần: {0}",
            "Giới hạn mua hàng tháng: {0}",
        ],
        YiGouMai: "Đã mua",
        Free: "Miễn phí",
        Buy: "Mua",
        Yuan: "{0}nhân dân tệ",
    },
    Date: {
        day: "Ngày",
        hour: "Giờ",
        minute: "Phút",
        second: "Giây",
    },
    TextHelper: {
        Negative: "Âm"
    },
    UiTimeMeter: {
        TimeStr1: "{0:D2}:{1:D2}:{2:D2}",
        TimeStr2: "{0}:{1}:{2}",
        TimeStr9: "{0}:{1}",
        TimeStr3: "{0} giờ {1} phút {2} giây",
        TimeStr4: "{0} ngày {1} giờ {2} phút",
        TimeStr5: "{0} ngày {1} giờ",
        TimeStr6: "{0}:{1:D2}:{2:D2}:{3:D2}",
        TimeStr7: "{0} giờ {1} phút",
        TimeStr8: "{0} phút {1} giây",

        TimeAgo: ["ngày", "giờ", "phút", "giây"]
    },
    Login: {
        RecentLogin: "Đăng nhập gần đây",
        Group: "nhóm {0}",
        NoRole: "Chưa có nhân vật",
        OtherLoginTitle: "Nhắc nhở",
        OtherLoginTips: "Tài khoản đã đăng nhập ở nơi khác,\nnhấn xác nhận để thoát.",
        SeverNameShow1: "Đăng nhập trước {0}máy chủ {1}",
        SeverNameShow2: "{0}phục vụ",
        RoleNameShow: "cấp độ {0} {1}",
        version: "Phiên bản tài nguyên: {0}",
        StateShow: {
            [0]: "Đóng",
            [1]: "Server mới",
            [2]: "Đông",
            [3]: "Đầy",
            [4]: "Thử nghiệm",
            [5]: "Bảo trì",
        },
        WaitTips: {
            def: "Đang kết nối lại…",
            tips1: "Vui lòng chờ…",
        },
        ServerTips: {
            NotOpenTips: "Máy chủ chưa mở, thời gian mở\n{0}-{1}-{2} {3:D2}:{4:D2}:{5:D2}",
            BadTips: {
                [0]: "Máy chủ đang đóng, tạm thời không thể vào",
                [4]: "Máy chủ đang thử nghiệm, tạm thời không thể vào",
                [5]: "Máy chủ đang bảo trì, không thể vào, vui lòng theo dõi thông báo",
            }
        }
    },
    RoleSetting: {
        TabInfo: "Thông tin nhân vật",
        TabSetting: "Cài đặt",
        TabNotice: "Cài đặt thông báo",
        TabMail: "Thư",

        Info: {
            LevelShow: "Lv.{0}",
            UidShow: "UID：{0}",
            ServerShow: "Máy chủ hiện tại: máy chủ {0}",
        },
        MailGet: ["Không được thu thập", "Đã nhận"],
        RewardGet: "Nhận thưởng",
        OK: "Xác nhận",
        Date: "{0}-{1}-{2}",
        Time: "{0:D2}:{1:D2}:{2:D2}",
        MailTip: "Bạn có thư mới, vui lòng kiểm tra",
    },
    Adventure: {
        mao_xian: "Mạo Hiểm",
        level: "Ải",
        tip: "Có thể nhận sau khi vượt chương {0}",
        CurBox: "Rương kho báu hàng ngày: {0}/ngày",
        NextBox: "{0}chiếc/ngày<color=#" + COLORSTR.Green1 + ">(Đạt {1})</color>",
    },
    Dungeon: {
        MainName: "Phó Bản",
        EnterNames: ["Boss", "Tháp Thí Luyện", "Viễn Hàng", "Tháp Cố Ma", "Tháp Minh Văn", "Lãnh Địa", "Thủ Hộ Thú Cưng"],
        ChiefNames: ["Boss Rương", "Boss Vàng", "Boss Thú Cưỡi"],
        LastTime: "Lượt còn lại: {0}",
        TodayLastTime: "Hôm nay còn {0} lượt",
        MopSureTitle: "Quét {0}",
        OneKey: "Quét nhanh",
        LevelLack: "Không đủ cấp",
        PassLack: "Cần vượt ải trước",
        OneKeyLack: "Hiện chưa thể quét",
        LevelNeed: "Mở ở cấp {0}",
        DiamondLack: "Không đủ kim cương",
    },
    Box: {
        cur_lv: "Cấp hiện tại:",
        next_lv: "Cấp tiếp theo:",
        box_up: "Nâng cấp rương",
        box_uping: "Đang nâng cấp rương...",
        time: "Thời gian:",
        tip: "Giữ <color=#ff3a3a{0}>được Chúa ban</color> và trang bị có chất lượng cao hơn",
        tip1: "Mở rương tự động đã kết thúc",
        tip2: "Số lượng rương bằng 0, có thể nhận qua Minh tưởng",
        tip3: "Đã đủ điều kiện nâng cấp",
        tip4: "Chưa đủ điều kiện nâng cấp",
        tip5: "Vé khiêu chiến đã đạt giới hạn",
        tip6: "Đã nhận được {0} vé thử thách hôm nay\nXác suất nhận được Vé Thử thách từ rương kho báu sẽ giảm đi rất nhiều",
        tip7: "Hãy xử lý trang bị trong rương hiện tại trước",
        tip8: "Mở khi đạt cấp {0}",
        tip9: "Sau đó có thể tiếp tục giảm thời gian",
        tip10: "Không đủ 5 rương",
        BtnReduceTime: "Giảm thời gian",
        Sale: "Bán",
        Enchant: "Phân giải",
        Tip10: "Có cơ hội nhận được <color=# khi mở hộp hàng ngày" + COLORSTR.Yellow3 + ">Thời trang tinh tế</color>",
        Tip11: "Các mặt hàng thời trang có sẵn hàng ngày: {0}/{1}",
        SellTips: "Sinh mệnh, công, thủ và tốc độ của trang bị này\nđều cao hơn trang bị hiện tại, vẫn xác nhận bán chứ?",
        ChangeState: ["Đã chuyển sang bán", "Đã chuyển sang phân giải"],
        goto: "Đi tới",
        getBox: "Nhận rương",
        tip11: "Có thể nhận rương bằng các cách sau"
    },
    BoxDraw: {
        TitleNames: {
            [14]: "Rương kho báu có khắc chữ",
            [9]: "rương kho báu thú cưng",
        }
    },
    Manual: {
        condition_desc: [
            "Đã đạt đến cấp độ {0}",
            "Rương kho báu được nâng cấp lên cấp {0}",
            "{0} rương kho báu đã được mở (tích lũy)",
        ],
        tip: "Phần thưởng này đã nhận",
        chen_hao: "hiệp sĩ đẳng cấp",
        add_money: "Tiền thưởng khi bán tiền vàng: {0}%"
    },
    UserProtocol: {
        Title1: "Thỏa thuận người dùng",
        Title2: "chính sách bảo mật",
    },
    MysteryShop: {
        refresh_limit: "Số vé làm mới còn lại:",
        limit_buy: "Giới hạn mua:",
        discount: "{0} giảm giá"
    },
    FastUse: {
        tip1: "Số lượng đã đạt giới hạn",
        tip2: "Không thể giảm thêm số lượng",
        tip3: "Số lượng sử dụng không thể bằng 0",
        tip4: "Không đủ {0}",
        tip5: "Số vé khiêu chiến đã đạt giới hạn",
    },
    Mount: {
        MainName: "Thú cưỡi",
        MainTitle: "Thú Cưỡi",
        Title: ["Thú Cưỡi", "Thám hiểm thú cưỡi"],
        LvTitle: "Lv.",
        LackItem: "Không đủ vật phẩm để nâng cấp",
        GradeTitle: "mức độ",
        LevelTitle: "lớp học",
        TimerShow: "/Giờ",
        ExploreShow: "người/giờ",
        ExploreAttr: "khám phá",
        LevelShow: "{0}Cấp độ{1}",
        UnlockError: "Thú cưỡi hiện tại chưa mở khóa",
        LackExplore: "Hiện chưa có thu hoạch thám hiểm",
        ComposeError: "Không đủ mảnh vỡ, vui lòng truy cập kho báu để vẽ",
        UnLockItemLackError: "Nếu bạn chưa nhận được thú cưỡi hiện tại, vui lòng đến cửa hàng bí ẩn để mua các mảnh vỡ.",
        LevelUpItemLackError: "{0} không đủ, vui lòng truy cập {1} để lấy",
        AwakenSuccess: "Mở khóa thành công",
        HuanHuaTip: "Đã hủy ảo hóa thú cưỡi",
        jie: "mức độ",
        MainTag: ["khai thác", "gắn kết", "Chuyển đổi"],
        EquipBagTitle: "khai thác kho",
        EquipSelectTitle: "Thiết bị cưỡi ngựa",
        EquipTypeName: ["mũ bảo hiểm ngựa", "áo giáp ngựa", "yên xe", "móng ngựa"],
        EmptyExAttr: "Chưa có thuộc tính",
        WashLimit: "Không thể khóa tất cả các mục",
        BuyHarnessTip: "Không đủ roi cưỡi",
        ResolveSuccess: "Phân giải thành công",
        UnlockSuccess: "Mở khóa thành công",
        EmptyEquip: "Chưa có",
        UnlockTitle: "Mở khóa lỗ",
        UnlockContent: "Bạn có chắc chắn muốn chi {0} kim cương để mở khóa lỗ vào không?",
        ResolveTitle: "Tháo dỡ dây nịt",
        ResolveContent: "Bạn có chắc chắn muốn phân tách {0} không? Bạn sẽ nhận được {1}{2}",
        WashTitle: "Huấn luyện khai thác ngựa",
        WashContent: "Các mục hiện đang tinh chỉnh bao gồm các mục có giá trị. Bạn có chắc chắn muốn tinh chỉnh? Việc tinh chỉnh sẽ mất các mục không được chọn.",
    },
    Trial: {
        TabTrialTower: "Tháp thử nghiệm",
        TabGuMoTower: "Tháp mê hoặc",
        TrialTower: {
            LayerShow: "Lớp {0}",
            RecordLayerShow: "Số tầng cao nhất trong số này: {0} tầng",
            RecordRankShow: "Xếp hạng của bản dùng thử này: {0}",
            RecordRankShowNone: "Xếp hạng của thử nghiệm này: Chưa có xếp hạng",
            RewardRankLater: "{0} trở lên",
            RankLayerShow: "lớp {0}",
            ItemShiLianDescShow: "Mỗi cấp độ tăng thêm {0}{1}",
            ItemShiLianDescShow2: "Cải thiện cấp độ {0}<color=#" + COLORSTR.Yellow5 + ">{1}</color>{2}",
            UseLockTips: "Lưới hiện tại chưa được mở khóa",
            BagEmptyTips: "Không thể trang bị vật phẩm trống",
            LockTips: "Yêu cầu {0} {1} để mở khóa",
            TimeShow: "Thời gian cho đến khi thời gian dùng thử kết thúc: {0}",
            SpoilNewTips: "Nhận chiến lợi phẩm mới: {0}",
            SpoilUpTips: "Chiến lợi phẩm: {0}, được nâng cấp lên cấp {1}",
            LevelNameShow: "Cấp độ {0}",
        },
        GuMoTower: {
            LayerShow: "Lớp {0}",
            ConditionFont: "Điều kiện {0}: {1}",
            StarReward: "{0} sao",
            DayReward0: "Tôi chưa thách thức Tháp Quỷ. Bạn có thể nhận được nó vào lúc 0:00 ngày hôm sau sau khi thử thách nó vào cùng ngày.",
            DayRewardGet: "nhận được",
            DayRewardGeted: "Đã nhận",
            RewardDescShow: "tắt {0}\nCó sẵn để sưu tập",
            RewardConditionShow: "Ngày tiếp theo sau thử thách hôm nay<color=#" + COLORSTR.Red5 + ">Chỉ có lúc 0:00</color>",
        },
        RankReward: "Xem trước phần thưởng xếp hạng",
        RankRewardTip: "Phần thưởng của Tháp thử nghiệm được tính toán dựa trên thứ hạng hàng tuần và được phân phối qua email.",
    },
    Fish: {
        MainName: "Khảo cổ học",
        MainTitle: "Khảo cổ học",
        TabToolUpLevel: "Tăng cường",
        TabToolUpGrade: "đột phá",
        BoxTypeShows: {
            [0]: "hóa thạch cổ đại",
            [1]: "quặng hiếm",
            [2]: "Kho báu di tích",
            [3]: "Sinh vật dưới lòng đất",
            [4]: "đồ sưu tầm",
        },
        WaBaoFailReason: {
            [-3]: "Xin lỗi, không có gì ở đây",
            [-2]: "Địa chất quá cứng và sức mạnh không thể xuyên thủng",
            [-1]: "Kho báu đã bị đánh cắp",
        },
        FishMain: {
            OrderProgressShow: "{0}/{1}"
        },
        FishOrder: {
            OrderProgressShow: "{0}/{1}",
            TimeShow: "<outline color=#" + COLORSTR.Green2 + " width=2><color=#" + COLORSTR.Green1 + ">{0}</color></outline> <outline color=#" + COLORSTR.Yellow2 + " width=2><color=#" + COLORSTR.Yellow1 + ">Tự động làm mới đơn hàng</color></outline>",
            DescShow: "Nhận {0}{1}",
            GetTips: "Nhận{0}x{1}",
        },
        FishMap: {
            MapGo: "Đi đến",
            MapLock: "Chưa mở khóa",
            MapUnLock: "Mở khóa",
            ConditionShow: {
                [0]: "Đạt cấp độ <color=#" + COLORSTR.Blue2 + ">{0}</color> cấp độ",
                [1]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> hóa thạch",
                [2]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> quặng",
                [3]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> kho báu",
                [4]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> sinh vật",
                [5]: "Thẻ phiêu lưu<color=#" + COLORSTR.Blue2 + ">{0}</color>Tắt",
            },
            ProgressShow: "<color=#{0}>{1}</color>/{2}",
            ArrowNextLock: "Cảnh trước không được mở khóa",
        },
        FishHandbook: {
            ProgressShow: "Đã mở khóa: {0}/{1}"
        },
        FishCollectReward: {
            AttrShow: "{0}：+{1}",
            CurLevel: "Cấp độ: {0}",
            CostNumEnough: "<color=#" + COLORSTR.Green3 + ">{0}/{1}</color>",
            CostNumNotEnough: "<color=#" + COLORSTR.Red1 + ">{0}</color><color=#" + COLORSTR.Yellow2 + ">/{1}</color>",
            TitleShows: {
                [0]: "đồ sưu tầm",
                [1]: "Hang động dưới biển",
                [2]: "hang rừng",
                [3]: "Hang Vọng",
            },
            UpSucc: "Nâng cấp thành công",
            ActiveSucc: "Kích hoạt thành công",
            BtnActive: "kích hoạt",
            BtnActived: "Đã kích hoạt",
        },
        FishSetting: {
            QuaDesc: {
                [0]: "Xuất sắc trở lên",
                [1]: "Xuất sắc trở lên",
                [2]: "Hiếm trở lên",
                [3]: "Sử thi trở lên",
                [4]: "Huyền thoại trở lên",
                [5]: "Chúa ban và cao hơn",
                [6]: "Thần đúc trở lên",
            },
            StopSucc: "dừng thành công",
        },
        FishGet: {
            AttrShow: "{0}：+{1}"
        },
        FishBox: {
            AttrShow: "{0}：+{1}",
            NextTips: "Mở khóa khi tủ trưng bày được nâng cấp lên cấp {0}"
        },
        FishBoxUp: {
            LevelCur: "Cấp độ hiện tại: {0}",
            LevelNext: "Cấp độ tiếp theo: {0}",
            unit: "cá nhân",
            AttrShows: {
                [1]: "Hóa thạch cổ đại:",
                [2]: "Quặng hiếm:",
                [3]: "Di tích bảo vật:",
                [4]: "Sinh vật dưới lòng đất:",
            },
            NeddTime: "thời gian:",
            TimeShow: "<outline color=#" + COLORSTR.Yellow2 + " width=2><color=#" + COLORSTR.Yellow1 + ">{0}</color></outline>",
            CanUpTips: "Đã đáp ứng yêu cầu nâng cấp",
        },
        FishToolUp: {
            LevelShow: "{0}Cấp độ{1}",
            TaskUpNo: "Chưa đạt đến giới hạn cấp độ hiện tại\nKhông thể xuyên thủng",
            ConditionShow: {
                [0]: "Đạt cấp độ <color=#" + COLORSTR.Blue2 + ">{0}</color> cấp độ",
                [1]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> hóa thạch cổ đại",
                [2]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> quặng quý hiếm",
                [3]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> kho báu di tích",
                [4]: "Đi sâu vào <color=#" + COLORSTR.Blue2 + ">{0}</color> sinh vật dưới lòng đất",
            },
            UpLevelSucc: "Củng cố thành công",
            UpLevelFail: "Đột phá lên cấp {0} có thể tiếp tục mạnh lên",
            UpGradeSucc: "Thành công đột phá",
        },
        FishInfo: {
            RecordShow: "Kích thước lịch sử: {0} cm"
        },
        WaBaoingTips: "Đang đào kho báu, xin hãy chờ đợi!",
        ItemTypeName: {
            [0]: "Kích thước khoáng sản",
            [1]: "May mắn",
            [2]: "sức mạnh",
            [3]: "Chống trộm",
            [4]: "giá bán",
        },
    },
    ShenQi: {
        MainName: "hiện vật",
        MainTitle: "hiện vật",
        ShenQiMain: {
            BtnDrawFree: "Miễn phí {0} lần",
            TimeShow: `<outline color=#${COLORSTR.Yellow2} width=${2}><color=#${COLORSTR.Green4}>{1}</color>thu được sau<color=#${COLORSTR.Green4}>{0}</color>Cơ hội làm mới miễn phí</outline>`,
            DrawingTips: "Trúng xổ số",
        },
        ShenQiRecord: {
            TitleShow: "Xem lịch sử",
            EnergyNum: "Năng lượng tạo tác x{0}",
            ItemName: "Nhận {0}",
            ItemNames: {
                [2]: "siêu đôi",
                [3]: "mảnh hiện vật",
            }
        },
        ShenQiInfo: {
            NumShow: "Các mảnh: {0}/{1}",
            Max: "Đã đầy cấp",
            NotActive: "Chưa kích hoạt",
            NotActiveTips: "Chưa kích hoạt, không thể trang bị",
            WearingTips: "Thần khí {0} đã được trang bị",
            BtnWear: "Trang bị",
            BtnWeard: "Đã trang bị",
        },
        ShenQiEnergy: {
            DescShow: "Năng lượng của hiện vật là không đủ. Tôi có nên sử dụng nó? <màu=#" + COLORSTR.Blue2 + ">{0}</color> các mảnh phổ quát thay vì nâng cấp"
        },
        ShenQiAttr: {
            QuaLevel: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>chất lượng xanh：Lv.{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>chất lượng màu xanh：Lv.{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>chất lượng cam：Lv.{0}</outline>`,
            },
            NextLevel0: "Chưa kích hoạt",
            NextLevel: "Nâng thêm {0} cấp để nhận tăng thuộc tính",
            DescShow: {
                [2]: `Mỗi lần hiện vật chất lượng xanh được cải thiện{0}cấp độ,{1}`,
                [3]: `Mỗi khi hiện vật chất lượng màu xanh được cải thiện{0}cấp độ,{1}`,
                [6]: `Mỗi lần hiện vật chất lượng màu cam được cải thiện{0}cấp độ,{1}`,
            },
        },
        ShenQiEnter: {
            QuaLevel: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>Lv.{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>Lv.{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>Lv.{0}</outline>`,
            },
            AttrShow: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>{0}</outline>`,
            },
            NotActive: "Chưa kích hoạt",
        }
    },
    Guild: {
        TabGuild: "Bang hội",
        TabGuildHelp: "Tương trợ",
        TabGuildInfo: "Thành viên",

        GuildTrain: {
            TabTrain: "Rèn luyện kỵ sĩ",
            TabTrainPrimary: "Thường",
            TabTrainAdvanced: "Cao cấp",

            LevelShow: `Tổng mức độ tập luyện：<color=#${COLORSTR.Yellow9}>{0}</color>`,
            PartNames: ["bài tập đầu", "bài tập tay", "tập thể dục", "bài tập cánh tay", "bài tập chân", "tập thể dục chân"],
            ConditionShow: [`Bài tập tổng hợp<color=#${COLORSTR.Red2}>{0}cấp độ</color>Mở khóa`, `Tập luyện nâng cao<color=#${COLORSTR.Red2}>{0}cấp độ</color>Mở khóa`],
            ResetTips: "Xác nhận sử dụng {0}{1} để đặt lại tất cả\nĐổi mới? Sau khi đặt lại, mức độ chuyển đổi sẽ bị xóa.\nvà trả lại tất cả tài nguyên",

            AdvancedOpenTips: "Mức độ luyện tập bình thường {0} đang mở",
        },
        GuildCreate: {
            NameNumTips1: "Độ dài của tên hiệp sĩ nhỏ hơn 2 và việc tạo ra không thành công.",
            NameNumTips2: "Độ dài của tên hiệp sĩ lớn hơn 12 và việc tạo ra không thành công.",
            CreateTips: "Bạn có chắc chắn muốn lập hiệp sĩ không?",
        },
        GuildInfo: {
            NoticeShowEmpty: "Trưởng nhóm rất lười biếng và chưa chỉnh sửa thông báo!",
            BtnOpers: ["từ bỏ", "trục xuất", "cuộc hẹn", "bị giáng chức", "chuyển khoản", "chuyển khoản"],
            DismissTips: "Bạn có chắc chắn muốn giải tán Hiệp sĩ không?",
        },
        GuildBoss: {
            ProgressValShow: "Lượng máu còn lại hiện tại: {0}%",
            TimesShow: "Số thử thách còn lại hôm nay: {0}",
            FightTips: "Bạn có chắc chắn chi {0}{1} để thách đấu BOSS không?",
            BtnGet: "nhận được",
            BtnGeted: "Đã nhận",
        },
        GuildHelp: {
            ContentShow: [
                "",
                "Người chơi \"{0}\" gia nhập Hiệp sĩ",
                "Người chơi \"{0}\" rời khỏi Hiệp sĩ",
                "Người chơi \"{0}\" chuyển trưởng nhóm sang \"{1}\"",
                "Người chơi \"{0}\" chuyển phó thủ lĩnh sang \"{1}\"",
                "",
                "Người chơi \"{0}\" được chỉ định \"{1}\" làm phó thủ lĩnh",
            ],
            ProgressValShow: `<color=#${COLORSTR.Green4}>{0}</color> / {1}`,
        },

        NameShow: "Tên bang: {0}",
        IdShow: "ID：{0}",
        NumShow: "Thành viên: <color=#{2}>{0}</color>/{1}",

        PositionShow: [`<color=#${COLORSTR.Yellow9}>lãnh đạo</color>`, `<color=#${COLORSTR.Blue4}>Phó trưởng phòng</color>`, "thành viên"]
    },
    Block: {
        MainTitle: "Khối xây dựng",
        BlockModel: {
            EmptyTips: "Vui lòng lấy bản vẽ trước",
            QuaShow: "{0}chất lượng màu"
        },
        BlockFill: {
            AttrShow: "{0}  +{1}",
            Wu: "không có",
            Block0Tips: "Model hiện tại chưa được lắp",
            BtnWear: "Thiết bị",
            BtnWearing: "Được trang bị",
        },
        BlockCompose: {
            SelNum: "Hãy chọn 3 khối xây dựng để tổng hợp",
            SelSame: "Vui lòng chọn các khối xây dựng có cùng chất lượng để tổng hợp",
            SelMap: "Vui lòng chọn các khối xây dựng chưa được gắn kết để tổng hợp",
            MaxMap: "Các khối xây dựng hiện tại đã đạt đến mức cao nhất và không thể tổng hợp thêm được nữa.",
            ComposeTips: "Bạn có chắc chắn muốn tổng hợp? quan hệ đối tác hiện tại\nTỷ lệ thành công là {0}%, tổng hợp\nThất bại sẽ dẫn đến mất ngẫu nhiên một viên gạch",
            FailTips: "Tổng hợp không thành công",
        },
        BlockAchieve: {
            TitleShow: "Hoàn thành mô hình {0} cùng lúc",
            ProgressShow: "({0}/{1})",
            AttrShow: "{0}：+{1}",
        },

        QuaDesc: {
            [0]: "xuất sắc",
            [1]: "Xuất sắc",
            [2]: "hiếm",
            [3]: "sử thi",
            // [4]: "huyền thoại",
            [5]: "Món quà của Chúa",
            [6]: "đúc thần thánh",
        },
        QuaColor: {
            [1]: "màu đỏ",
            [2]: "màu vàng",
            [3]: "màu xanh da trời",
            [4]: "màu xanh lá",
        },
        All: "tất cả"
    },
    NewServerCompetition: {
        RankNames: {
            [0]: "đấu trường",
            [1]: "Viên đá linh hồn vòng tròn ma thuật",
            [2]: "cấp độ nhân vật",
            [3]: "Tháp mê hoặc",
            [4]: "cuộc phiêu lưu",
            [5]: "thú cưng",
            [6]: "vòng tròn ma thuật",
            [7]: "bản đồ sao",
            [8]: "gắn kết",
            [9]: "thời trang",
        },
        RankVal: {
            [0]: `< color=#${COLORSTR.Yellow1} > Xếp hạng：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [1]: `< color=#${COLORSTR.Yellow1} > Mức độ tổng thể：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [2]: `< color=#${COLORSTR.Yellow1} > cấp độ：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [3]: `< color=#${COLORSTR.Yellow1}> xếp hạng sao：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [4]: `< color=#${COLORSTR.Yellow1}> cấp độ：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [5]: `< color=#${COLORSTR.Yellow1}> Tổng cấp đá quý：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [6]: `< color=#${COLORSTR.Yellow1}> Mức độ tổng thể：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [7]: `< color=#${COLORSTR.Yellow1}> Mức độ tổng thể：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [8]: `< color=#${COLORSTR.Yellow1}> Tổng mức thức tỉnh：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [9]: `< color=#${COLORSTR.Yellow1}> Mức độ tổng thể：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
        },
        RankEmptyVal: {
            [0]: `< color=#${COLORSTR.Red7}> Cần đạt thứ hạng：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [1]: `< color=#${COLORSTR.Red7}> Cần đạt đến trình độ tổng thể：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [2]: `< color=#${COLORSTR.Red7}> Cần đạt cấp độ：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [3]: `< color=#${COLORSTR.Red7}> Yêu cầu xếp hạng sao：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [4]: `< color=#${COLORSTR.Red7}> Cần đạt đến trình độ：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [5]: `< color=#${COLORSTR.Red7}> Yêu cầu tổng cấp đá quý：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [6]: `< color=#${COLORSTR.Red7}> Cần đạt đến trình độ tổng thể：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [7]: `< color=#${COLORSTR.Red7}> Cần đạt đến trình độ tổng thể：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [8]: `< color=#${COLORSTR.Red7}> Cần đạt đến mức độ thức tỉnh tổng thể：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [9]: `< color=#${COLORSTR.Red7}> Cần đạt đến trình độ tổng thể：</color><color=#${COLORSTR.Red7}>{0}</color > `,
        },
        // RewardVal: {
        // [0]: `Xếp hạng: { 0 } `,
        // [1]: `Tổng cấp độ: { 0 } `,
        // [2]: `Cấp độ: { 0 } `,
        // [3]: `Đánh giá: { 0 } `,
        // [4]: `Cấp độ: { 0 } `,
        // [5]: `Tổng cấp đá quý: { 0 } `,
        // [6]: `Tổng cấp độ: { 0 } `,
        // [7]: `Tổng cấp độ: { 0 } `,
        // [8]: `Tổng mức thức tỉnh: { 0 } `,
        // [9]: `Tổng cấp độ: { 0 } `,
        // },
        RewardVal: {
            [0]: `Xếp hạng：{0} `,
            [1]: `Xếp hạng：{0} `,
            [2]: `Xếp hạng：{0} `,
            [3]: `Xếp hạng：{0} `,
            [4]: `Xếp hạng：{0} `,
            [5]: `Xếp hạng：{0} `,
            [6]: `Xếp hạng：{0} `,
            [7]: `Xếp hạng：{0} `,
            [8]: `Xếp hạng：{0} `,
            [9]: `Xếp hạng：{0} `,
        },
        NoRank: "Không có trong danh sách",
        TimeShow: "Thời gian còn lại của cuộc thi: {0}",
        ActEnd: "Đã giải quyết",
        OpenDay: "{0} sẽ được mở trong tương lai",
    },
    AdEquity: {
        DescShow: [
            { desc_show: `< color=#${COLORSTR.Green3}> bỏ qua miễn phí < /color>Quảng cáo tăng tốc nâng cấp rương kho báu` },
            { desc_show: `<color=#${COLORSTR.Green3}>bỏ qua miễn phí</color>Quảng cáo tăng tốc nâng cấp bộ sưu tập` },
            { desc_show: `<color=#${COLORSTR.Green3}>bỏ qua miễn phí</color>Phần thưởng chứng chỉ hiệp sĩ` },
            { desc_show: `<color=#${COLORSTR.Green3}>bỏ qua miễn phí</color>Quảng cáo kim cương phúc lợi hàng ngày` },
            { desc_show: `<color=#${COLORSTR.Green3}>bỏ qua miễn phí</color>Hoạt động phúc lợi khen thưởng quảng cáo` },
        ],
        productName: "quyền quảng cáo",
    },
    KnightCard: {
        BtnBuyedShow: "Đã mua",
        BtnGetShow: "nhận được",
        BtnGetedShow: "Đã nhận",
        GetedTips: "Đã nhận được hôm nay",
        GetNotTips: "Vui lòng nhận phần thưởng trước đó trước",
        TimeShow: `thời gian còn lại：<color=#${COLORSTR.Green4}>{0}</color>`,
    },
    DataHelper: {
        DaXie: ["không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "Chín", "mười", "Trăm", "nghìn", "Mười nghìn"],
        FanTi: ["không", "một", "hai", "Ba", "bốn", "Ngô", "đất", "bảy", "tám", "Cửu", "nhặt lên", "Trăm", "nghìn", "mười nghìn"],
    },
    Battle: {
        tip: "Tải không thành công",
        round: "Vòng {0}",
        loading: "Đang tải trận chiến...",
    },
    Angel: {
        MainTitle: "Pháp Trận",
        level_add: "Cộng theo cấp",
        grade_add: "Cộng theo bậc",
        tip: "Hoàn thành nhiệm vụ chính tuyến để kích hoạt hồn thạch pháp trận",
        jie: "mức độ",
        tip2: "Phải kích hoạt mới có thể ảo hóa",
        tip3: "Ảo hóa thành công",
        Angel: "Pháp trận",
        HuanHua: "Ảo hóa",
        HuanHuaTip: "Đã hủy ảo hóa pháp trận",
        Title: "Pháp Trận",
    },
    Arena: {
        day_reward: "Thưởng xếp hạng ngày",
        day_reward_tip: "Đấu trường phát thưởng qua thư lúc 24h mỗi ngày theo thứ hạng",
        week_reward: "Thưởng xếp hạng tuần",
        week_reward_tip: "Đấu trường phát thưởng qua thư lúc 24h Chủ nhật theo thứ hạng",
        RankScoreShow: "Điểm: {0}",
        rank_title: "Bảng xếp hạng tuần này",
        result_desc: [
            "Thử thách thành công: +{0}",
            "Thử thách không thành công: -{0}",
            "Bảo vệ thành công",
            "Phòng thủ thất bại: -{0}",
            "Trả thù thành công: +{0}",
        ],
        result_desc2: [
            "Thử thách thành công: {0} +{1}",
            "Thử thách không thành công: {0} {1}",
            "Bảo vệ thành công",
            "Phòng thủ không thành công: {0} {1}",
            "Trả thù thành công: {0} +{1}",
        ],
        challenged: "Tổng số tuần này:",
        cur_rank: "Xếp hạng hiện tại:",
        cur_score: "tích phân:",
        cap: "Sức mạnh chiến đấu:",
        score: "tích phân:",
        tip: "Không đủ lượt khiêu chiến",
        hour_before: "giờ",
        min_before: "phút trước",
        arena: "Đấu Trường",
        tip2: "Người chơi hiện tại đã ẩn thông tin nhân vật",
        score_desc: "Điểm đấu trường:",
        no_rank: "Chưa vào bảng xếp hạng",
        rank: "Không. {0}",
        NoPet: "Chưa có thú cưng ra trận",
    },
    StarMap: {
        MainTitle: "bản đồ sao",
        SuperStarTitle: "Cây tài năng",
        Grade: "mức độ",
        TypeName: ["nhân vật chính", "thú cưng"],
        GradeLock: "Mở sau khi kích hoạt tất cả các lỗ tài năng ở cấp độ trước",
        LevelMax: "Lỗ hổng tài năng này đã ở mức đầy đủ",
        PointOper: ["kích hoạt", "nâng cấp"],
        LinkError: "Các lỗ tài năng liền kề không được kích hoạt",
        LinkLevelError: "Lỗ tài năng phía trước có thể được nâng cấp nếu đạt đến cấp độ {0}.",
        ItemLack: "Không đủ vật phẩm cần thiết để nâng cấp",
        Cost: "tiêu thụ",
        ResetTitle: "cài lại",
        ResetItemLack: "Không đủ vật phẩm cần thiết để thiết lập lại",
        StarPointMax: "Lỗ hổng tài năng này đã đạt đến mức tối đa",
        PointUpLevelError: "Tất cả các hố tài năng có thể được nâng cấp lên cấp độ tiếp theo nếu chúng đạt đến cấp độ {0}.",
        MaxLevel: "Thiên hà hiện tại đã ở mức đầy đủ",
    },
    StarMapSuperNew: {
        tabTitles: [null, "tấn công", "phòng thủ", "mạng sống", "tốc độ"],
        activeTIp: "Cần kích hoạt điểm tài năng trước",
    },
    Skill: {
        MainTitle: "Kỹ năng",
        TabSkill: "Kỹ năng chủ động",
        TabTalent: "Thiên phú",
        Learn: "Học",
        LevelUp: "Nâng cấp",
        MaxLevel: "Đã đầy cấp",
        OneKeyLevelUp: "Nâng cấp nhanh",
        Refresh: "Làm mới",
        Unlearned: "Chưa học",
        EmptyViewTips: "Nhấn tab phía trên để xem kỹ năng chủ động hoặc thiên phú, rồi thao tác học/nâng cấp ở bên dưới",
        NoDetail: "Chưa có mô tả chi tiết",
        CurrentLevelLabel: "Cấp hiện tại:",
        TargetLabel: "Mục tiêu:",
        TargetEnemy: "Địch",
        TargetAlly: "Đồng minh",
        TargetUnit: "mục tiêu",
        FeatureLabel: "Đặc tính:",
        BasicAttackDesc: "Đánh thường",
        FlagDodge: "Có thể né",
        FlagCrit: "Có thể bạo kích",
        FlagCombo: "Có thể liên kích",
        FlagLeech: "Có thể hút máu",
        FlagLucky: "Có thể gây choáng",
        FlagCounter: "Có thể phản kích",
    },
    Pet: {
        pet: "thú cưng",
        PetInfo: "thông tin thú cưng",
        PetLevelUp: "Nâng cấp thú cưng",
        PetAdvence: "thức tỉnh thú cưng",
        PetSkill: "Kỹ năng thú cưng",
        last_pet_tip: "Cấm thả thú cưng cuối cùng",
        exp: "Kinh nghiệm*{0}",
        advence_order: "Thức tỉnh·{0} cấp độ",
        select_pet_tip: "Vui lòng chọn thú cưng",
        no_pet_tip: "Vẫn chưa có thú cưng",
        pet_embattle_succ: "Pet ra trận thành công",
        pet_outbattle_succ: "Thú cưng đã tham chiến thành công",
        pet_changebattle_succ: "Thay thế thú cưng thành công",
        pet_changepos_succ: "Đổi thú cưng thành công",
        pet_outbattle_desc: "Đã mở khóa cấp độ {0}",
        grade_level: "{0}Cấp độ{1}",
        lock: "Chưa mở khóa",
        select_skill_tip: "Vui lòng chọn một cuốn sách kỹ năng",
        cost_tip: "Khóa {0} kỹ năng và tiêu thụ {1} mỗi khi bạn học một kỹ năng.",
        pet_skill_tab: ["Sách kỹ năng cơ bản", "Sách kỹ năng nâng cao", "Sách kỹ năng hàng đầu"],
        no_select_skill: "Không có sách kỹ năng nào được chọn",
        return_tip: "Thú cưng đã được thả thành công",
        AttrShow: "{0}:",
        ts_gem_name: "Đá quý đặc biệt dành cho thú cưng cấp {0}",
        CostPetGrade: "Thú cưng cấp độ {0}",
        AdvenceTip: "Bạn có chắc chắn tiêu thụ <color=#" + COLORSTR.Green3 + ">[+{0}] Thức tỉnh, sau khi thức tỉnh<color=#" + COLORSTR.Green3 + "> [+{1}]</color>Những viên đá quý được đeo sẽ bị loại bỏ và sách kỹ năng cũng như kinh nghiệm sẽ không được trả lại.",
        AdvenceTip2: "Bạn có chắc chắn sẽ thức tỉnh? Sau khi thức tỉnh<color=#" + COLORSTR.Green3 + "> [+{0}]</color>Những viên đá quý được đeo sẽ bị loại bỏ và sách kỹ năng cũng như kinh nghiệm sẽ không được trả lại.",
        WashTip: "Tinh chỉnh sẽ nhận được <color=# mới" + COLORSTR.Yellow3 + ">Gắn</color>, khi đạt đến giới hạn trên, sàng lọc sẽ là <color=#" + COLORSTR.Yellow3 + ">Thay đổi phụ tố</color>, sau khi kiểm tra\nCác phụ kiện sẽ không biến mất và giới hạn trên của các phụ kiện hiện tại là cấp độ đá quý hiện tại.",
        PetSkillMap: {
            tab: ["Kỹ năng cơ bản", "kỹ năng nâng cao", "kỹ năng hàng đầu"],
        },
        PetSkillCover: "Cấp độ kỹ năng được chọn cao hơn kỹ năng học tập. Bạn có chắc chắn nó được bảo hiểm?",
        GemNotUp: "Không đủ nguyên liệu để nâng cấp",
        GemSet: "Cài đặt đá quý",
        Tip: "Hãy đến sự kiện để nhận đá quý thú cưng",
        GemStore: "kho đá quý",
        GemWash: "Đánh bóng đá quý",
        GemUp: "Nâng cấp đá quý",
        GemMaxTip: "Cấp độ đã đầy",
        GemUpTip: "Nâng cấp đá quý sẽ tiêu tốn <color=#" + COLORSTR.Yellow3 + ">1 viên ngọc cùng cấp</color>, những viên ngọc đã được trang bị sẽ không bị ảnh hưởng",
        OneKeyTip: "Vui lòng chọn tài liệu để quảng cáo bằng một cú nhấp chuột",
        CanUp: "Có thể nâng cấp",
        NoItems: "Nguyên liệu không đủ",
        UpTip: "Yêu cầu {0} {1} ({2})",
        UpTip2: "Vẫn cần {0} {1} để nâng cấp ({2})",
        EvolTitle: "sự tiến hóa của thú cưng",
        NoItemsForEvol: "Không đủ nguyên liệu để phát triển",
        downTip: "Ra khỏi trận chiến",
        upTip3: "Đi vào trận chiến",
        EmIndexTip: "Vị trí {0}",
        RateTitle: "Xác suất nhóm giải thưởng",
        RateTag: ["Căn cứ", "trình độ cao", "sang trọng"],
        SkillUnlockTip: "Vui lòng mở khóa lưới kỹ năng trước",
        SkillUnlockForamt: "Bạn có muốn chi {0}{1} để mở khóa các khe kỹ năng thú cưng không?",
    },
    Escort: {
        Name: "hộ tống",
        Title1: "Tàu hộ tống",
        Title2: "Xem trước phần thưởng xếp hạng",
        Title3: "Kỷ lục hộ tống",
        Title4: "kỷ lục đánh chặn",
        Title5: "Xếp hạng",
        Title6: "Cải tiến chất lượng",
        Title7: "chặn",
        //Level:"<color=#{0}>{1}cấp độ</color>",
        Level: "Cấp độ {0}",
        Time: "Hộ tống: {0} phút",
        TabbarName1: "Xếp hạng cướp bóc",
        TabbarName2: "Danh sách xếp hạng điểm",
        RankNum: "{0}-{1}",
        RankNum2: "{0} trở lên",
        BoatName: "tàu buôn lớp {0}",
        MaxLevel: "Đã đầy đủ cấp độ",
        MaxTip: "Chất lượng tàu đã đạt đến mức hoàn hảo",
        QuaNoChange: "Nâng cấp chất lượng tàu không thành công",
        MaxCount: "Số lượng người hộ tống đã đạt đến",
        TimeDesc: "{1} tháng {2} ngày {0}",
        ShengYu1: "Số lần chặn còn lại: {0}/{1}",
        Count: "{0}/{1}",
        ShengYu2: "Số lần còn lại: {0}",
        JiFen: "Điểm: {0}",
        Time2: "{0:D2}:{1:D2}",
        EscortStart: "Bắt đầu hộ tống tàu buôn lớp {0}",
        MySelf: "Không thể chặn tàu của bạn",
        ItemDesc: "{0}x{1}",
        InterTip: "Con tàu không thể bị chặn sau khi vượt quá số lần chặn.",
        EscortTip: "Đã có một con tàu ra khơi. Nó chỉ có thể khởi hành trở lại sau khi hoàn thành việc hộ tống hiện tại.",
        HelpTip: "Giải cứu thành công",
        GhostTimeDesc: "Cuộc trốn thoát của con tàu ma:",
    },
    GemAtelier: {
        MainTitle: "đá quý",
        Title: "đá quý",
        InsetTitle: "Cài đặt đá quý",
        UpGradeTitle: "Nâng cấp đá quý",
        TagName: ["Bản vẽ thông thường", "bản vẽ đặc biệt"],
        LvShow: "Lv.",
        LackSpError: "{0} có thể nhận được thông qua {1}",
        LevelError: "{0} có thể nhận được thông qua {1}",
        GemTagError: "Loại đá quý này chưa có được",
        LackItemError: "Nguyên liệu không đủ",
        LevelGradeError: "Cấp độ khác với đá quý mục tiêu",
        LevelShow: "cấp:",
        DrawUnAct: "Thuộc tính bản vẽ chưa được kích hoạt",
        FullDrawTips: "Có thể đặt tối đa 6 viên đá quý bản thiết kế",
        MixTitle: "nâng cấp",
        DrawUpDateSuccess: "Bản thiết kế đá quý đã được nâng cấp thành công và được nâng cấp lên cấp {0}.",
        PicUp: "Nâng cấp hoàn tất",
        ChangeTarget: "Đá quý có thể thay thế",
        ChangeGem: "chuyển đổi đá quý",
        GemUpEmpty: "Vui lòng chọn mục tiêu nâng cấp trước",
        ChangeEmpty: "Vui lòng chọn mục tiêu chuyển đổi trước tiên",
        GemChangeEmpty: "Vui lòng chọn mục tiêu cần chuyển đổi trước",
        GemOneKeyUp: "Nâng cấp bằng một cú nhấp chuột",
        GemUpTip: "Nâng cấp đá quý sẽ tiêu tốn <color=#" + COLORSTR.Yellow3 + ">3 viên ngọc cùng cấp</color>",
        GemUpNeed: "Yêu cầu đá quý cấp {0} {1}",
        GemDrawTitle: "Cần đá quý",
        OneKeyGemLack: "Không đủ đá quý cần thiết để nâng cấp bằng một cú nhấp chuột",
        OneKeyLevelLow: "Nâng cấp bằng một cú nhấp chuột yêu cầu bản vẽ từ cấp 1 trở lên",
        OneKeyGemLackNeed: "Thiếu {0}{1}",
    },
    CommodityGuildItem: {
        Yuanjia: "Giá gốc: {0}",
        LimitBuy: ["Tổng giới hạn mua hàng:", "Giới hạn mua hàng ngày:"],
        JinDu: "{0}/{1}",
        Zhe: "{0} giảm giá",
        Cost: "{0}nhân dân tệ",
        StarZhe: "giảm giá từ {0} đến {1}",
    },
    CaveLoot: {
        Zhe: "{0} giảm giá",
        BaoDiDesc: "Khám phá lại<color=#" + COLORSTR.Yellow3 + ">{0}</color> Bạn sẽ nhận được đạo cụ hiếm mỗi lần",
        UseNum: "{0}/{1}",
        GaiLu: "{0}%",
        Free: "miễn phí",
        XianGou: ["Giới hạn mua hàng ngày:", "Giới hạn mua sự kiện:"],
        RechargeDesc: "Số tiền nạp tích lũy {0} nhân dân tệ",
        RechargeNum: "<color=#" + COLORSTR.Green3 + ">{0}</color>",
        RechargeNum1: "<color=#" + COLORSTR.Yellow5 + ">{0}</color>",
        RechargeNum2: "Số lần nạp tích lũy<color=#" + COLORSTR.Yellow5 + ">{0}</color>nhân dân tệ",

    },
    BoxManor: {
        xiangou: ["Giới hạn mua {0} lần", "Giới hạn mua hàng {0} lần mỗi ngày"],
    },
    IntegralTurntable: {
        UseNum: "{0}/{1}",
        must: `máy bơm<color=#${COLORSTR.Yellow3}>{0}</color>Mỗi lần bạn thắng`,
        current: `Điểm hiện tại：<color=#${COLORSTR.Yellow1}>{0}</color>`,
        probability: "xác suất bánh xe",
        cherish: "Trân trọng đạo cụ",
        rests: "Khác khác",
        source: "Nguồn điểm",
        consume: "Kiếm điểm bằng cách tiêu thụ các đạo cụ sau",
        score: "{0}điểm/phần",
        DrawingTips: "Trúng xổ số",
        onScore: "Không đủ điểm",
        GaiLu: "{0}%",
    },
    ExclusiveGift: {
        Purchase: `Chỉ mua hàng{0}lần，giá trị<color=#${COLORSTR.Yellow9}>{1}</color>Nhân dân tệ！`,
        Price: "¥{0}",
    },
    ClothShop: {
        ClothShopTitle: ["thời trang", "gắn kết", "vòng tròn ma thuật", "thú cưng"],
        Price: "¥{0}",
        QuaDesc: {
            [3]: "sử thi",
            [4]: "huyền thoại",
            [5]: "Món quà của Chúa",
            [6]: "đúc thần thánh",
            [7]: "đặc biệt",
        },
    },
    Recharge: {
        noOpen: "Nạp tiền không mở",
        Diamond: "kim cương",
        GoldType: [
            "¥",
            "$",
            "NT$",
            "₩",
            "₫"
        ],
        ItemBuyDesc: "Có nên tiêu thụ {0} thẻ phổ thông hay không",
        ItemNum: "Thẻ phổ quát: {0}",
    },
    LoopMine: {
        MainTitle: "Săn tìm kho báu",
        Title: "chiếm giữ kho báu",
        BtnTitle: "Truy tìm kho báu {0} lần",
        TagName: ["Săn tìm kho báu nhí", "Truy tìm kho báu nâng cao"],
        ItemLackError: "Không đủ đạo cụ",
        ItemLast: "Còn lại: {0} lần",
        RewardGot: "Đã nhận được phần thưởng",
        RewardLackNum: "Không đủ may mắn",
        RecordTitle: "Kỷ lục săn tìm kho báu",
        RecordCell: "{0} đã nhận được {1}",
        NeedReflush: "Tổng giải thưởng đã bị xóa, vui lòng làm mới",
    },
    MainOther: {
        shop: "Trung tâm mua sắm",
        manual: "Hướng dẫn nâng cao",
        mystery_shop: "cửa hàng bí ẩn",
        friend_rank: "Xếp hạng bạn bè",
        knight_card: "Giấy chứng nhận hiệp sĩ",
        guild: "hiệp sĩ",
        item_recycling: "Tái chế vật phẩm",
    },
    InviteFriends: {
        InviteDesc: "Mời<màu=#" + COLORSTR.Green3 + ">{0}</color> bạn bè",
    },
    Fashion: {
        Title: "thời trang",
        MainTitle: "thời trang",
        TabName: ["mũ bảo hiểm", "cánh tay", "áo giáp", "cái khiên"],
        Title2: ["kích hoạt", "ngôi sao đang lên", "Đã đạt đến giới hạn"],
        CostDesc: ["Tiêu thụ kích hoạt", "Nâng cấp mức tiêu thụ"],
        FashionMax: "Thời trang này đã đạt đến mức tối đa",
        LevelTip: "Thời trang chưa được kích hoạt",
        HuanHuaSuccess: "Mặc thành công",
        HuanHuaCancel: "Mặc bị hủy",
        ActiveTips: "Đảm bảo giá <color=#" + COLORSTR.Yellow5 + ">{0}</color>{1}Kích hoạt\n<màu=#" + COLORSTR.Green3 + ">[{2}]</color>?"
    },
    OpenServer: {
        BoxOpenType: ["{0}", "Mở {0} rương kho báu", "Cấp rương kho báu đạt đến {0}"],
        LimitError: "Điều kiện nhận không được đáp ứng",
        TimeLimit: "Thời gian hoạt động còn lại",
        NeoServerNeedError: "Không đủ mặt hàng để mua",
        NeoServerTimeError: "Số lượng mua đã hết",
        NeoServerLimitType: ["", "Giới hạn mua:", "Giới hạn mua hôm nay:"],
        SevensDayShow: "Ngày {0}",
        SevensDaysDaysError: "Vui lòng quay lại vào ngày mai để nhận phần thưởng của bạn!",
        SevensDaysDaysEndError: "Tất cả phần thưởng đã được nhận",
        SevensDaysDone: "Đã nhận",
        SevensDaysWait: "nhận được",
        NeoShopOffShow: "nếp gấp",
        NeoShopFLushTime: "Làm mới miễn phí sau {0}",
        NeoShopFlushError: "Không đủ tiền cần thiết để làm mới",
        NeoShopTimesError: "Sản phẩm này đã đạt đến giới hạn mua cho lần làm mới này",
        NeoShopbuyError: "Cần không đủ tiền để mua mặt hàng này",
        NeoShopbuyDiaError: "Không đủ kim cương vui lòng đi nạp tiền",
        Title: ["Đăng nhập trong bảy ngày", "Chúc may mắn ra khỏi hộp", "Ưu đãi đặc biệt cho máy chủ mới", "cửa hàng ngoại hình"],
        NeoShopFlushFree: "Làm mới miễn phí",
        NeoShopFlush: "làm cho khỏe lại",
        NeoShopSellDone: "Bán hết",
        NeoShopPriceLack: "không đủ",
        NoteEnoughLevel: "Trình độ là không đủ. Vui lòng thử lại sau khi nâng cấp.",
        BoxNotEnoughLevel: "Cấp độ của rương kho báu là không đủ. Hãy thử lại sau khi nâng cấp.",
        ItemNotEnough: "Không đủ số lượng lệnh săn tìm kho báu",
        ShopDayFlush: "Số lần làm mới ngày hôm nay:",
        ShopDayFlushEnd: "Số lần làm mới hôm nay đã hết",
    },
    FightAccount: {
        Scoure: [`{0}<color=#${COLORSTR.Green1}>（+{1}）</color>`, `{0}<color=${COLORSTR.Red1}>（{1}）</color>`],
    },
    LeiChong: {
        WeiDaCheng: "Bạn chưa đạt được mục tiêu thu thập của mình!",
        Desc: "Phần thưởng nạp lại tích lũy là {0} nhân dân tệ",
        NextTip: "{0}nhân dân tệ",
        ValueTip: "Giá trị ¥{0}",
        ValueTip2: "Giá trị {0}",
        BtnTitle: "¥{0}",
        BtnTitle2: "¥ {0}",
        BtnTitle3: "Sẽ được thu thập",
        TimeStr: `<color=#${COLORSTR.Green4}>{0}</color>điểm<color=#${COLORSTR.Green4}>{1}</color>giây`,
    },
    LuckyGift: {
        LuckyGift: "Món quà may mắn",
        value: "giá trị",
    },
    MonthlyCard: {
        UnLockGet: "Mở khóa nhận ngay",
        DailyGet: "Đăng nhập mỗi ngày có thể nhận",
        Tip: "Hôm nay đã nhận",
        MonthlyCard: "Thẻ tháng",
        FishSpeed2: "Tốc độ đào bảo tăng gấp 2",
    },
    FunOpen: {
        LevelTip: "Mở khi nhân vật đạt cấp {0}",
        TaskTip: "Nhiệm vụ chưa hoàn thành, hãy hoàn thành rồi quay lại trải nghiệm",
        OpenTip: "Tính năng đã mở"
    },
    Task: {
        Finsh: "Hoàn thành",
    },
    GetWay: {
        LevelShow: "Cấp sử dụng:"
    },
    Shop: {
        limit_desc: [
            "",
            "Giới hạn ngày",
            "Giới hạn tuần",
            "Giới hạn vĩnh viễn",
        ],
        Box: "Rương ma pháp",
    },
    FastBuy: {
        FastBuy: "Mua nhanh",
        tip: "Số lượng không thể bằng 0",
        desc: "Xác nhận mua nhanh {0} {1}",
    },
    CommonGet: {
        AttrShow: "{0}：               +{1}",
        Split: ["      ", "      ", "      ", "      ", "      ", "", "      ", "      ", "      ", "      " //10
            , "      ", "", "", "", "", "", "", ""],
    },
    CDKeyExchange: {
        RetCode: [
            "Đổi thưởng thành công, phần thưởng đã được gửi đến email",
            "Lỗi mã đổi quà",
            "không thể tái sử dụng",
            "Lỗi máy chủ",
            "Mã đổi thưởng đã hết hạn",
            "Mã đổi quà đã được sử dụng",
            "Vui lòng đổi quà sau khi đạt đến cấp độ quy định",
            "Các lỗi khác",
            "Mã đổi thưởng đã hết hạn",
            "Số tiền gửi tích lũy không đủ",
        ],
        EmptyHint: "Vui lòng nhập mã đổi thưởng",
        OtherError: "Lỗi không xác định [%d]",
    },
    TodayShare: {
        Status: "Phần thưởng chia sẻ của ngày hôm nay: {0}/1",
        BtnStatus: ["chia sẻ", "Nhận trực tiếp", "Đã nhận", "nhận được"],
        FetchDone: "Bạn đã nhận được phần thưởng chia sẻ ngày hôm nay",
    },
    ScoreFund: {
        title: 'Đạt mức xếp hạng（{0}/{1}）',
        ScoreFund: "Quỹ xếp hạng",
    },
    Inscription: {
        MainTitle: "chữ khắc",
        ResolveTitle: "Phân rã dòng chữ",
        SelectTitle: "Chọn dòng chữ",
        AtlasTitle: "Sách minh họa dòng chữ",
        UnLockTips: "Vượt qua cấp độ {0} của Tháp khắc chữ\nMở khóa vị trí lỗ khắc chữ {1}",
        UnLockPopTips: "Cần vượt qua cấp độ {0} của Tháp khắc để mở khóa",
        UpGradeLack: "Nguyên liệu không đủ",
        AtlasCoreItemTitle: "dòng chữ cốt lõi",
        AtlasNomalDefaultTitle: "Được mở khóa theo mặc định",
        AtlasNomalTowerTitle: "Mở khóa cấp độ {0} của Tháp khắc chữ",
        ResolveEmpty: "Không có dòng chữ nào được chọn",
        NeedEquiped: "Chưa đeo dòng chữ",
        BtnExchange: "thay thế",
        BtnEquip: "khảm",
        BtnSExchange: "thay thế",
        BtnSEquip: "khảm",
        SkillStart: "Hiệu ứng kỹ năng:",
        DetailCurShow: ["Phần thưởng thuộc tính", "Hiệu ứng kỹ năng:"],
        BtnUp: "nâng cấp",
        BtnUpMax: "Đã đầy đủ cấp độ",
        Tower: {
            LayerShow: "Lớp {0}",
            DescShow: `Làm thủ tục hải quan <color=#${COLORSTR.White}>{0}đóng</color> thu được sau`,
            DayRewardGet: "nhận được",
            DayRewardGeted: "Đã nhận",
            DayReward0Tips: "Tôi chưa thách thức Tháp khắc chữ. Bạn có thể nhận được phần thưởng sau khi thử thách nó.",
        },
        Turntable: {
            // DescShow1: ``Chi phí cho một lần rút <color=#${COLORSTR.Green4}>{0}{1}, </color>Chi phí cho mười lần rút liên tiếp mỗi lần <color=#${COLORSTR.Green4}>{0}{2}</color>`,
            DescShow1: `hàng ngày3Số lần rút thăm miễn phí cho quảng cáo`,
            DescShow2: `Giành giải thưởng lớn và nhận phần thưởng ngẫu nhiên，Và bạn có thể có được tất cả phần còn lại của vòng này\nPhần thưởng để tiến vào vòng tiếp theo`,
            RoundShow: "Số vòng hiện tại: Vòng {0}",
            NumShow: "Số lần còn lại: <color=#{0}>{1}</color> lần",
            DrawingTips: "Trúng xổ số",
            DrawNumTips: "{0} là không đủ",
            BtnDraw1: "Vẽ 1 lần",
            BtnDraw5: "Vẽ 5 lần",
            FreeTimes: "Còn {0} lần miễn phí hôm nay",
            AdTips: "Bạn có thể lấy lại miễn phí sau",
            BtnFree: "Nhận nó miễn phí",
        },
        MainTag: ["Trái tim khắc chữ", "Sách minh họa dòng chữ", "Phân rã dòng chữ", "Rương kho báu có khắc chữ"],
        BtnEmptyAttr: "Vui lòng cài đặt dòng chữ và kiểm tra lại.",
    },
    AngelFes: {
        Title: "Lễ kỷ niệm vòng tròn ma thuật",
        TagName: ["Nâng cấp vòng tròn ma thuật", "Nâng cấp trang phục thần thánh", "Giảm giá lớn"],
        TaskUnComplete: "Chưa hoàn thành",
        BtnComplete: "nhận được",
        BtnDone: "Đã nhận",
        BtnUnComplete: "Chưa đạt được",
        GiftLimit: ["{0}", "{0}", "Giới hạn mua hàng ngày: {0}", "Giới hạn mua: {0}"],
        Offset: "nếp gấp",
        LimitBuyFull: "Số lượng mua đã hết",
    },
    AffordPresent: {
        NumShow: "Số lượng:",
        Days: "Ngày {0}",
        BuyWait: "Giờ thu gom vẫn chưa đến",
    },
    adv: {
        daily: "Xem video thành công và nhận được {0} kim cương",
        speed: "Đã xem video thành công và thời gian nâng cấp đã giảm bớt {0} phút.",
        inscription_turntable: "Xem thành công video và nhận được {0} cơ hội xổ số ghi tên",
        knight_card: "Đã xem video thành công và nhận được {0}{0}",
        weekend_rechagre: "Đã xem video thành công, tăng hạn ngạch {0}",
        canvas_ling: "Nếu xem video thành công bạn sẽ nhận được lệnh truy tìm kho báu.",
        level_fun: "Xem video thành công và nhận phần thưởng gấp đôi",
        box_fun: "Xem video thành công và nhận phần thưởng gấp đôi",
        today_share: "Xem video thành công và nhận phần thưởng gấp đôi",
        draw: "Sau khi xem video, nhiệm vụ đã hoàn thành và quá trình xổ số bắt đầu.",
        territory_refresh: "Xem video thành công, làm mới tất cả tài nguyên",
    },
    StarMapFes: {
        Title: "Lễ kỷ niệm biểu đồ sao",
        TagName: ["Bản đồ sao nhân vật chính", "biểu đồ sao thú cưng", "Cải thiện biểu đồ sao"],
        TaskUnComplete: "Chưa hoàn thành",
        BtnComplete: "nhận được",
        BtnDone: "Đã nhận",
        BtnUnComplete: "Chưa đạt được",
        GiftLimit: ["{0}", "{0}", "Giới hạn mua hàng ngày: {0}", "Giới hạn mua: {0}"],
        Offset: "nếp gấp",
        LimitBuyFull: "Số lượng mua đã hết",
        BtnFree: "miễn phí",
    },
    TrailChengJiu: {
        JingJieCost: "Mở khóa thăng tiến {0}"
    },
    ContinuePresent: {
        RatePreView: "Xem trước phần thưởng",
        TaskAND: "hoặc",
        TaksShow: ["Nạp tiền {0}", "Mời bạn bè{0}"],
        DayShow: "Ngày {0}",
        BigCountShow: "Nhiệm vụ ngày thứ {0} đã được hoàn thành. Bạn có thể nhận giải thưởng lớn bằng cách hoàn thành thêm {1} ngày nữa.",
        BigCountPro: "Tiến trình: {0}/{1}",
        UnCompleteTips: "Nhiệm vụ chưa hoàn thành và không thể thu thập được."
    },
    FriendsRank: {
        Title: "Xếp hạng bạn bè"
    },
    WeekHaoLi: {
        XianGou: ["{0}", "Tổng giới hạn mua hàng: {0}", "Giới hạn mua hàng ngày: {0}"],
        Cost: "¥ {0}",
        TimeLimit: "Thời gian còn lại của sự kiện:",
        // TimeStr5: "<color=#${COLORSTR.Yellow1}>{0}</color>ngày<color=#${COLORSTR.Yellow1}>{1</color> giờ",
        TimeStr5: `<color=#${COLORSTR.Yellow3}>{0}</color>ngày<color=#${COLORSTR.Yellow3}>{1}</color>thời gian`,
    },
    Enchant: {
        Title: "sự mê hoặc",
        IsActive: ["Đã kích hoạt{0}/{1}", "Chưa kích hoạt"],
        State: ["Đang kích hoạt...", "Chưa kích hoạt"],
        CancelEnchant: "Vật liệu đã sử dụng sẽ không được trả lại sau khi hủy. Bạn có chắc chắn sẽ từ bỏ thời gian hiện có?",
        StillEnchant: "Số lần kích hoạt bùa mê đã đạt đến giới hạn trên. Phần thưởng thuộc tính không thể nhận được từ lần kích hoạt này. Bạn có muốn tiếp tục không?",
        EnchantLevel: "Cấp độ phù phép {0}/{1}",
        ShowBuffDesc: "{0}:{1}%",
        ShowBuffDesc2: "{0}%",
        NeedNUm: "<color=#{0}>{1}</color>/{2} ",
        NoNum: "Không có vật liệu mê hoặc được chọn.",
    },
    PeakArena: {
        EnterName: ["đấu trường", "Đấu trường liên máy chủ"],
        NeoPointShow: "tích phân:",
        PointShow: "điểm",
        RankTag: ["Bảng xếp hạng hôm nay", "Bảng xếp hạng tuần này"],
        DailyTitle: "Bảng xếp hạng hôm nay",
        WeeklyTitle: "Bảng xếp hạng tuần này",
        RankTitle: "Xếp hạng",
        RecordTitle: "kỷ lục chiến đấu",
        TimePlus: "phía trước",
        LevelShow: "lv.",
        BtnRevenge: "sự trả thù",
        RewardTag: ["Phần thưởng hôm nay", "Phần thưởng tuần này"],
        BtnFlush: "làm cho khỏe lại",
        ServerShow: "Máy chủ: máy chủ {0}",
        FlushWaiting: "Vui lòng đợi thời gian làm mới kết thúc",
        FlushLack: "{0} là không đủ",
        MainChallenged: "Mục tiêu này đã được thử thách",
        RecordShow: ["thất bại", "thành công"],
        RecordType: ["phòng thủ", "thử thách"],
        WeekEndTimer: "Đếm ngược tuần này: <color=" + COLORSTR.Green4 + ">{0}</color>",
        ChallengeBtn: "thử thách",
        ColdTips: "Vui lòng đợi thời gian hồi chiêu kết thúc",
        score_desc: "Điểm đấu trường liên máy chủ:"
    },
    Territory: {
        MainName: "Lãnh thổ",
        Title1: "Lãnh thổ",
        Title2: "chộp lấy",
        Title3: "Nhật ký lãnh thổ",
        Level: "Cấp lãnh thổ; {0}",
        BotNum: "Không được sử dụng: {0}",
        BotFree: "Đã sử dụng: {0}",
        CurRewardCount: "Thời gian thu thập hiện tại: {0}/{1}",
        StateDesc: "trạng thái {0}",
        SpeedDesc: "(Tốc độ thu thập là {0}%)",
        BotState: ["hào hứng", "Bình thường", "Mệt mỏi", "hết hiệu lực"],
        BotDesc: "Trạng thái thu thập hiện tại: trạng thái {0}, tốc độ thu thập là {1}%",
        BotNum2: "Số lượng người phục vụ cây: {0}",
        Level2: "Lv.{0}",
        Limit: "Giới hạn trên {0}",
        UseNum: "{0}/{1}",
        UseNum2: `<color=#${COLORSTR.Red1}>{0}</color>/{1}`,
        ErrorText1: "Đã vượt quá giới hạn trên",
        ErrorText2: "Vượt quá số lượng sở hữu",
        ErrorText3: "Có quá nhiều rương kho báu và không thể thu thập được.",
        ErrorText4: "Hiện tại không có người phục vụ cây nào.",
        ErrorText5: "Người phục vụ cây đang bận, vui lòng quay lại sau",
        BotNum3: "Số lượng người phục vụ cây: {0}/{1}",
        FlushTime: "Có thể được làm mới sau {0}",
        NameList: ["lãnh thổ của tôi", "lãnh thổ của người khác"],
        BotDoing: "thu thập",
        LockDesc: "Đã mở khóa cấp độ {0}",
        DayDesc: "{0} ngày trước",
        HourDesc: "{0} giờ trước",
        MinuDesc: "{0} phút trước",
        DateDesc: "{0}Tháng{1}",
        BuySucc: "Mua thành công",
        BuyLimit: "Giới hạn mua hàng",
        BoxTip: "Có quá nhiều rương kho báu và không thể thu thập được.",
        NameList2: ["lãnh thổ lân cận", "lãnh thổ của kẻ thù"],
        TitleList2: ["Chưa có đối thủ", "Chưa có kẻ thù"],
        MatchText: "Trong khi bạn không ở đây",
        BtnDesc: "sự trả thù",
        Price: "¥{0}",
        Price2: "Giá trị¥{0}",
        ActNoOpen: "Sự kiện chưa được bắt đầu",
        refreshAd: "Sau khi xem video, hãy làm mới tất cả tài nguyên"
    },
    MingXiang: {
        Box: "Rương kho báu hàng ngày <color=#" + COLORSTR.Green1 + ">{0}</color>/ngày",
        MaxTip: "Số lượng lấy hàng nhanh hôm nay đã đạt giới hạn trên",
        NoTip: "Chưa có phần thưởng nhàn rỗi nào",
    },
    WeekLianChong: {
        OneDayNeedRecharge1: `Nạp tiền một ngày\nđầy đủ<color=#${COLORSTR.Green1}>{0}</color>Nhân dân tệ`,
        OneDayNeedRecharge2: `Nạp tiền một ngày\nđầy đủ<color=#${COLORSTR.Blue1}>{0}</color>Nhân dân tệ`,
        OneDayNeedRecharge3: `Nạp tiền một ngày\nđầy đủ<color=#${COLORSTR.Yellow9}>{0}</color>Nhân dân tệ`,
        DayDesc: "Ngày {0}",
        NeedRecharge: "Nạp lại {0} nhân dân tệ để nhận được một sự thay thế",
        TodatRecharge: `Đã tính phí hôm nay：<color=#${COLORSTR.Yellow8}>{0}</color>Nhân dân tệ`,
        TimeStr5: `<color=#${COLORSTR.Green4}>{0}</color>ngày<color=#${COLORSTR.Green4}>{1}</color>thời gian`,
    },
    FundAdv: {
        title: "Nhận gấp đôi số tiền",
        LevelFundAdvTip: "Sau khi xem hết quảng cáo, bạn có thể nhận được phần thưởng gấp đôi"
    },
    LimitCoreDraw: {
        FreeLimitTime: "Còn lại {0} lần",
    },
    CoreCrisis: {
        CoreName: ["", "Núi Trái Tim", "Trái tim của vòng tròn", "trái tim đá quý", "biểu đồ trái tim của ngôi sao", "Trái tim khắc chữ", "Trái tim hiện vật"],
        CoreLimitTips: "{0}Không đủ cấp độ",
        CoreLimitForGemTips: "{0} không đủ cấp độ để tiếp tục khảm.",
        MaxTip: "Đã đạt mức tối đa",
    },
    ItemRecycling: {
        Title: "Tái chế thần tượng",
        Title2: "Cung cấp tài liệu",
        ExpValue: `<color=#${COLORSTR.Yellow9}>{0}</color>/{1}`,
        ExpValue2: `<color=#${COLORSTR.Yellow9}>{0}</color><color=#${COLORSTR.Green4}>+{1}</color>/{2}`,
        MaxLevel: "Đã đầy đủ cấp độ",
        NoSelect: "Chưa có mục nào được chọn",
    },
    PetGuard: {
        MainTitle: "Thử thách người giám hộ thú cưng",
        LayTitle: "Lớp {0}",
        ChallengeError: "Vui lòng hoàn thành thử thách ở cấp độ trước trước",
        AllChallengeComplete: "Tất cả các thử thách ở cấp độ này đã được hoàn thành",
        BtnChallengeDone: "Thử thách đã hoàn thành",
        BtnChallengeStart: "Bắt đầu thử thách",
    },
    PetHuanHua: {
        Tip1: "Thiếu {0}",
        Tip2: "Chưa mở",
        upTips: "Nâng cấp thành công",
        repTips: "Thay thế thành công",
        BtnTitle1: "Đã đầy đủ cấp độ",
        BtnTitle2: "Đã chọn",
        numTip0: `<color=#${COLORSTR.Red5}>{0}</color>/{1}`,
        numTip1: `<color=#${COLORSTR.Yellow2}>{0}</color>/{1}`,
    },
    ShenQiDuoBao: {
        TabTitle: ["Phần thưởng hiện vật", "Khuyến mãi hiện vật"],
        Tip1: "Thiếu {0}",
        TimeShow: ["bầu trời", "giờ", "điểm"],
        BtnGot: "Đã nhận",
        BtnDoing: "Chưa hoàn thành",
        BtnWait: "nhận được",
        LimitType: ["", "Đã mua", "Giới hạn mua hàng ngày", "Giới hạn mua hàng"],
        Free: "miễn phí",
        ValueShow: "Giá trị:￥",
        ValueIconShow: "giá trị:",
        UnComplete: "Nhiệm vụ chưa hoàn thành",
        RewardGot: "Đã nhận được phần thưởng",
        LimitBuy: "Giới hạn mua đã hết",
    },
    MerlinMagic: {
        Title: ["phòng thu thập", "sách minh họa", "Thư viện lớn"],
        Title2: ["Sắp xếp theo chất lượng", "Sắp xếp chủ động và bị động"],
        QuaDesc: ["xuất sắc", "hiếm", "sử thi", "Món quà của Chúa", "đúc thần thánh"],
    }
}

export let TextHelperWord: { [key: number]: string } = {
    [0]: "không",
    [1]: "một",
    [2]: "hai",
    [3]: "ba",
    [4]: "bốn",
    [5]: "năm",
    [6]: "sáu",
    [7]: "bảy",
    [8]: "tám",
    [9]: "Chín"
}
export let TextHelperUnits: { [key: number]: string } = {
    [1]: "mười",
    [2]: "Trăm",
    [3]: "nghìn",
    [4]: "Mười nghìn",
}


export let AttrListIconName: { [key: number]: string } = {
    // [BATTLE_ATTR.ATTACK]: "attr_gongji",
    // [BATTLE_ATTR.ARMOR]: "attr_fangyu",
    // [BATTLE_ATTR.HP]: "attr_maxhp",
    // [BATTLE_ATTR.SPEED]: "attr_speed",
}

export let DateString: { [key: string]: string } = {
    ["day"]: "bầu trời",
    ["hour"]: "giờ",
    ["minute"]: "điểm",
    ["second"]: "Thứ hai",
}

export let AttrListName: { [key: number]: string } = {
    [BATTLE_ATTR.BATTLE_ATTR_MIN]: "tùy ý",
    [BATTLE_ATTR.HP]: "mạng sống",            // Sự sống Trong trường hợp bình thường, khi giá trị sự sống giảm xuống 0, trận chiến thất bại
    [BATTLE_ATTR.ATTACK]: "tấn công",          // Tấn công tăng sát thương gây ra
    [BATTLE_ATTR.ARMOR]: "phòng thủ",          // Phòng thủ Giảm sát thương nhận vào
    [BATTLE_ATTR.SPEED]: "tốc độ",          //Tốc độ Người chơi có tốc độ cao hơn sẽ tấn công đầu tiên trong vòng đấu
    [BATTLE_ATTR.TRUE_DAMAGE]: "thiệt hại cuối cùng",      // thiệt hại cuối cùng

    [BATTLE_ATTR.VAMPIRIC]: "Ma cà rồng",        // Hút máu // Dựa vào sát thương mà hồi mạng theo phần trăm hút máu // Số lượng hút máu = Sát thương gây ra * (là hút máu - b bỏ qua việc hút máu)
    [BATTLE_ATTR.COUNTER]: "phản công",        //Phản công//Phản công: Khi bị tấn công có khả năng tung đòn tấn công ngay lập tức, có thể làm gián đoạn đòn combo của đối thủ. Bạn không thể phản công khi bị choáng //Tỷ lệ phản công = phản công - b bỏ qua phản công
    [BATTLE_ATTR.COMBO]: "bột",          // Combo // Khi tấn công có xác suất tấn công lại và xác suất sẽ giảm sau mỗi combo // Tỷ lệ combo = một combo - b bỏ qua combo
    [BATTLE_ATTR.EVASION]: "né tránh",        // Né tránh // Có khả năng bạn sẽ không bị tổn hại gì cả
    [BATTLE_ATTR.CRITICAL]: "đòn chí mạng",        //Đòn chí mạng//Đòn tấn công có cơ hội gây sát thương gấp 2 lần và không thể tránh được đòn chí mạng.
    [BATTLE_ATTR.STUN]: "Choáng",          // Choáng // Có khả năng làm choáng đối thủ khi tấn công khiến nó không thể di chuyển // Tỷ lệ choáng = choáng - b bỏ qua choáng

    [BATTLE_ATTR.VAMPIRIC_IMMUNITY]: "Bỏ qua việc hút máu",    //Bỏ qua việc hút máu//Giảm tỷ lệ hút máu của đối thủ
    [BATTLE_ATTR.COUNTER_IMMUNITY]: "bỏ qua phản công",    //Bỏ qua phản đòn//Giảm khả năng phản công của đối phương
    [BATTLE_ATTR.COMBO_IMMUNITY]: "Bỏ qua combo",      //Bỏ qua combo//Giảm xác suất combo của đối thủ
    [BATTLE_ATTR.EVASION_IMMUNITY]: "Bỏ qua né tránh",    //Bỏ qua việc né tránh//Giảm khả năng né tránh của đối thủ
    [BATTLE_ATTR.CRITICAL_IMMUNITY]: "Bỏ qua các đòn chí mạng",    //Bỏ qua các đòn chí mạng//Giảm khả năng trúng đòn chí mạng của đối thủ
    [BATTLE_ATTR.STUN_IMMUNITY]: "Bỏ qua choáng",      //Bỏ qua choáng//Giảm khả năng bị choáng của đối thủ

    [BATTLE_ATTR.TYRANNY]: "chuyên chế",        // Bạo lực//Hệ số sát thương chí mạng tăng lên, 10% nghĩa là đòn chí mạng gây sát thương gấp 2,1 lần
    [BATTLE_ATTR.BENEVOLENCE]: "lòng nhân từ",      //Benevolence//Benevolence: Giảm sát thương thêm khi bạn nhận một đòn chí mạng và bù đắp cho sự bạo lực của bên kia.
    [BATTLE_ATTR.MUDDY]: "lầy lội",          // Bùn // Giảm tốc độ của đối thủ // Trận chiến bắt đầu có hiệu lực khiến đối thủ thay đổi tốc độ hiện tại * (1 - Bùn)
    [BATTLE_ATTR.INTERDICTION]: "Không điều trị",      // Điều trị bị cấm // Giảm tỷ lệ phần trăm của tất cả các hiệu ứng hồi phục sự sống của đối thủ. Khi đạt 100%, đối thủ không thể nhận được bất kỳ sự hồi phục sinh lực nào.
    [BATTLE_ATTR.REJUVENATION]: "hồi đáp",      //Hồi phục//Ở hiệp thứ năm, hồi phục sinh mệnh theo phần trăm máu tối đa
    [BATTLE_ATTR.BULLYING]: "bắt nạt",        //Bắt nạt//Khi máu của đối thủ thấp hơn 50%, sẽ gây thêm sát thương
    [BATTLE_ATTR.PILLAGE]: "Cướp tiền",        // Loot // Nhận thêm tiền vàng trong đấu trường
    [BATTLE_ATTR.GLADIATUS]: "đấu sĩ",        //Đấu sĩ//Tăng số lượng vé thử thách có thể mang theo
    [BATTLE_ATTR.MONEY_ADD]: "thương gia",
    [BATTLE_ATTR.HP_PER]: "tỷ lệ sức khỏe",
    [BATTLE_ATTR.ATTACK_PER]: "tỷ lệ tấn công",
    [BATTLE_ATTR.ARMOR_PER]: "tỷ lệ phòng thủ",
    [BATTLE_ATTR.SPEED_PER]: "phần trăm tốc độ",
    [BATTLE_ATTR.FISH_ATTR_1]: "Kích thước khoáng sản",
    [BATTLE_ATTR.FISH_ATTR_2]: "May mắn",
    [BATTLE_ATTR.FISH_ATTR_3]: "sức mạnh",
    [BATTLE_ATTR.FISH_ATTR_4]: "Chống trộm",
    [BATTLE_ATTR.FISH_ATTR_5]: "giá bán",
}

export let AttrListDesc: { [key: number]: string } = {
    [BATTLE_ATTR.HP]: "tăng tuổi thọ",
    [BATTLE_ATTR.ATTACK]: "Tăng sát thương",
    [BATTLE_ATTR.ARMOR]: "Giảm thiệt hại",
    [BATTLE_ATTR.SPEED]: "Tăng tốc độ phát hành",
    [BATTLE_ATTR.TRUE_DAMAGE]: "thiệt hại cuối cùng",

    [BATTLE_ATTR.VAMPIRIC]: "Phục hồi phần trăm thiệt hại",
    [BATTLE_ATTR.COUNTER]: "Phản đòn khi bị tấn công",
    [BATTLE_ATTR.COMBO]: "tấn công lần nữa",
    [BATTLE_ATTR.EVASION]: "Né tránh đòn tấn công của đối thủ",
    [BATTLE_ATTR.CRITICAL]: "Gây sát thương gấp đôi",
    [BATTLE_ATTR.STUN]: "Làm choáng váng đối thủ",

    [BATTLE_ATTR.VAMPIRIC_IMMUNITY]: "Giảm khả năng hút máu của đối thủ",
    [BATTLE_ATTR.COUNTER_IMMUNITY]: "Giảm khả năng phản công của đối thủ",
    [BATTLE_ATTR.COMBO_IMMUNITY]: "Giảm combo của đối thủ",
    [BATTLE_ATTR.EVASION_IMMUNITY]: "Giảm khả năng né tránh của đối thủ",
    [BATTLE_ATTR.CRITICAL_IMMUNITY]: "Giảm đòn chí mạng của đối thủ",
    [BATTLE_ATTR.STUN_IMMUNITY]: "Giảm choáng của đối thủ",

    [BATTLE_ATTR.TYRANNY]: "Tăng sát thương chí mạng",
    [BATTLE_ATTR.BENEVOLENCE]: "Giảm sát thương chí mạng của đối thủ",
    [BATTLE_ATTR.MUDDY]: "Giảm tốc độ của đối thủ",
    [BATTLE_ATTR.INTERDICTION]: "Giảm khả năng hồi phục sinh mệnh của đối thủ",
    [BATTLE_ATTR.REJUVENATION]: "Ở vòng thứ năm, sự sống sẽ được phục hồi dựa trên phần trăm máu tối đa.",
    [BATTLE_ATTR.BULLYING]: "Tuổi thọ càng thấp thì sát thương càng cao.",
    [BATTLE_ATTR.PILLAGE]: "Tiền vàng đấu trường tăng",
    [BATTLE_ATTR.GLADIATUS]: "Số cuộn thử thách được thực hiện +1",
    [BATTLE_ATTR.MONEY_ADD]: "Kiếm tiền từ việc bán thiết bị",

}

export let EquipQuality: { [key: number]: string } = {
    [1]: "【Bình thường】",
    [2]: "【Xuất sắc】",
    [3]: "[Tinh tế]",
    [4]: "【Hiếm】",
    [5]: "【Sử thi】",
    [6]: "[Huyền thoại]",
    [7]: "[Chúa ban]",
    [8]: "[Được rèn bởi Chúa]",
}
export let EquipName: { [key: number]: string } = {
    [EQUIP_TYPE.ER_HUAN]: "bông tai",
    [EQUIP_TYPE.XIANG_LIAN]: "vòng cổ",
    [EQUIP_TYPE.TOU_KUI]: "mũ bảo hiểm",
    [EQUIP_TYPE.HU_WAN]: "Dây đeo cổ tay",
    [EQUIP_TYPE.JIAN_BANG]: "cuốn sách ma thuật",
    [EQUIP_TYPE.KAI_JIA]: "áo giáp",
    [EQUIP_TYPE.YAO_DAI]: "thắt lưng",
    [EQUIP_TYPE.JIE_ZHI]: "nhẫn",
    [EQUIP_TYPE.WU_QI]: "cánh tay",
    [EQUIP_TYPE.KU_ZI]: "vòng đeo tay",
    [EQUIP_TYPE.XIE_ZI]: "giày",
    [EQUIP_TYPE.DUN_PAI]: "cái khiên",
}
