import { COLORSTR } from "./ColorEnum"
import { BATTLE_ATTR, EQUIP_TYPE } from "./CommonEnum"

export var Language = {
    Common: {
        Confirm: "确认",
        Wan: "万",
        QianWan: "千万",
        Yi: "亿",
        Reincarnation: "{0}转{1}星",
        shengji: "升级",
        jiasu: "加速",
        add: "增加",
        LevelShow: "Lv.{0}",
        NotHasTip: "不足",
        buy_limit: "购买次数已达上限",
        refresh_limit: "剩余刷新次数不足",
        use: "使用",
        buy: "购买",
        other: "其 他",
        level: "等级",
        OpenLevel: "{0}级开启",
        up_grade: "进阶",
        up_level: "升级",
        active: "激活",
        unActive: "未激活",
        rank: "排行",
        basic_attr: "基础属性",
        add_attr: "附加属性",
        NoTitle: "暂无称号",
        Explain: "说明",
        NotOpenTips: "功能未开放",
        CloseTip: "{0}秒后自动关闭",
        GetWayTip: ",请前往{0}获取",
        NameServer: "{0}(S.{1})",
        AdColdTime: "冷却未完成，CD倒数完后可再次点击观看广告",
        AdFreeTime: "免费次数已用完",
        bannedWordTip: "不能含有敏感词",
        ActShow: "活动",
        ColorName: {
            [1]: "白",
            [2]: "绿",
            [3]: "蓝",
            [4]: "紫",
            [5]: "黄",
            [6]: "橙",
            [7]: "红",
            [8]: "粉",
            [9]: "彩",
        },
        OperWaitTips: "操作过于频繁",
    },
    ActCommon: {
        YiLingQu: "已领取",
        LingQu: "领取",
        ChongZhi: "充值",
        JiangLiYiLingQu: "奖励已领取",
        WeiDaCheng: "未达成",
        XianGou: [
            "",
            "",
            "日限购：{0}",
            "周限购：{0}",
            "月限购:{0}",
        ],
        YiGouMai: "已购买",
        Free: "免费",
        Buy: "购买",
        Yuan: "{0}元",
    },
    Date: {
        day: "天",
        hour: "时",
        minute: "分",
        second: "秒",
    },
    TextHelper: {
        Negative: "负"
    },
    UiTimeMeter: {
        TimeStr1: "{0:D2}:{1:D2}:{2:D2}",
        TimeStr2: "{0}:{1}:{2}",
        TimeStr9: "{0}:{1}",
        TimeStr3: "{0}时{1}分{2}秒",
        TimeStr4: "{0}天{1}时{2}分",
        TimeStr5: "{0}天{1}时",
        TimeStr6: "{0}:{1:D2}:{2:D2}:{3:D2}",
        TimeStr7: "{0}时{1}分",
        TimeStr8: "{0}分{1}秒",

        TimeAgo: ["天", "小时", "分钟", "秒"]
    },
    Login: {
        RecentLogin: "最近登录",
        Group: "{0}组",
        NoRole: "暂无角色",
        OtherLoginTitle: "提示",
        OtherLoginTips: "账号在别处登陆，\n点击确定退出。",
        SeverNameShow1: "{0}服 {1}前登陆",
        SeverNameShow2: "{0}服",
        RoleNameShow: "{0} {1}级",
        version: "资源版本号:{0}",
        StateShow: {
            [0]: "关闭",
            [1]: "新服",
            [2]: "拥挤",
            [3]: "爆满",
            [4]: "测试",
            [5]: "维护",
        },
        WaitTips: {
            def: "重连中…",
            tips1: "请稍后…",
        },
        ServerTips: {
            NotOpenTips: "服务器暂未开启，开启时间\n{0}-{1}-{2} {3:D2}:{4:D2}:{5:D2}",
            BadTips: {
                [0]: "服务器关闭中，暂时无法进入",
                [4]: "服务器测试中，暂时无法进入",
                [5]: "服务器维护中，无法进入，维护时\n间请留意公告",
            }
        }
    },
    RoleSetting: {
        TabInfo: "角色信息",
        TabSetting: "设置",
        TabNotice: "通知设置",
        TabMail: "邮件",

        Info: {
            LevelShow: "Lv.{0}",
            UidShow: "UID：{0}",
            ServerShow: "当前服务器：{0}服",
        },
        MailGet: ["未领取", "已领取"],
        RewardGet: "领取奖励",
        OK: "确定",
        Date: "{0}-{1}-{2}",
        Time: "{0:D2}:{1:D2}:{2:D2}",
        MailTip: "您有新的邮件，请注意查收",
    },
    Adventure: {
        mao_xian: "冒 险",
        level: "关卡",
        tip: "通关章节{0}后可获得",
        CurBox: "每日宝箱：{0}个/天",
        NextBox: "{0}个/天<color=#" + COLORSTR.Green1 + ">(通关{1})</color>",
    },
    Dungeon: {
        MainName: "副 本",
        EnterNames: ["首领", "试炼之塔", "远航", "锢魔之塔", "铭文之塔", "领地", "宠物守护"],
        // ChiefNames: ["宝箱首领", "金币首领", "夺宝首领"],
        ChiefNames: ["宝箱首领", "金币首领", "坐骑首领"],
        LastTime: "剩余次数：{0}",
        TodayLastTime: "今日剩余{0}次",
        MopSureTitle: "{0}扫荡",
        OneKey: "一键扫荡",
        LevelLack: "等级不足",
        PassLack: "需要通关上一关卡",
        OneKeyLack: "暂无可用扫荡",
        LevelNeed: "{0}级解锁",
        DiamondLack: "钻石不足",
    },
    Box: {
        cur_lv: "当前等级：",
        next_lv: "下一等级：",
        box_up: "升级宝箱",
        box_uping: "宝箱升级中...",
        time: "时间:",
        tip: "保留<color=#ff3a3a{0}>天赐的</color>及以上品质装备",
        tip1: "自动开箱结束了",
        tip2: "宝箱数量为0，可通过冥想获取",
        tip3: "已达到升级条件",
        tip4: "未达到升级条件",
        tip5: "挑战券已达上限",
        tip6: "今日已获{0}张挑战券\n从宝箱中获得挑战券的概率将大幅降低",
        tip7: "请先处理当前宝箱中的装备",
        tip8: "等级提升到{0}级后开启",
        tip9: "之后可以再次减少时间",
        tip10: "宝箱数量不足5个",
        BtnReduceTime: "减少时间",
        Sale: "出售",
        Enchant: "分解",
        Tip10: "每日开箱有几率获得<color=#" + COLORSTR.Yellow3 + ">精美时装</color>",
        Tip11: "每日可获得时装：{0}/{1}",
        SellTips: "出售装备的生命、攻击、防御、速度都\n高于当前装备，是否确定出售。",
        ChangeState: ["当前已切换为出售", "当前已切换为分解"],
        goto: "前往",
        getBox: "获取宝箱",
        tip11: "可通过以下方式获取宝箱"
    },
    BoxDraw: {
        TitleNames: {
            [14]: "铭文宝箱",
            [9]: "宠物宝箱",
        }
    },
    Manual: {
        condition_desc: [
            "等级达到{0}级",
            "宝箱升级到{0}级",
            "宝箱开了{0}个（累计）",
        ],
        tip: "该奖励已领取",
        chen_hao: "级骑士",
        add_money: "出售金币加成：{0}%"
    },
    UserProtocol: {
        Title1: "用户协议",
        Title2: "隐私政策",
    },
    MysteryShop: {
        refresh_limit: "剩余刷新券数量：",
        limit_buy: "限购：",
        discount: "{0}折"
    },
    FastUse: {
        tip1: "数量已达上限",
        tip2: "数量不能再减少了",
        tip3: "使用数量不能为0",
        tip4: "{0}不足",
        tip5: "挑战券数量已达上限",
    },
    Mount: {
        MainName: "坐骑",
        MainTitle: "坐 骑",
        Title: ["坐 骑", "坐骑探索"],
        LvTitle: "Lv.",
        LackItem: "升级所需道具不足",
        GradeTitle: "阶",
        LevelTitle: "级",
        TimerShow: "/小时",
        ExploreShow: "个/小时",
        ExploreAttr: "探索",
        LevelShow: "{0}阶{1}级",
        UnlockError: "当前坐骑未解锁",
        LackExplore: "暂无探索收益",
        ComposeError: "碎片不足，请前往夺宝抽取",
        UnLockItemLackError: "未获得当前坐骑，请前往神秘商店购买碎片",
        LevelUpItemLackError: "{0}不足,请前往{1}获取",
        AwakenSuccess: "解锁成功",
        HuanHuaTip: "已取消坐骑幻化",
        jie: "阶",
        MainTag: ["马具", "坐骑", "幻化"],
        EquipBagTitle: "马具仓库",
        EquipSelectTitle: "马具装备",
        EquipTypeName: ["马盔", "马铠", "马鞍", "马蹄"],
        EmptyExAttr: "暂无属性",
        WashLimit: "不能锁定全部词条",
        BuyHarnessTip: "马鞭数量不足",
        ResolveSuccess: "分解成功",
        UnlockSuccess: "解锁成功",
        EmptyEquip: "暂无",
        UnlockTitle: "孔位解锁",
        UnlockContent: "确定要花费{0}钻石解锁词条孔位吗？",
        ResolveTitle: "马具分解",
        ResolveContent: "确定要分解{0}吗，将会获得{1}{2}个",
        WashTitle: "马具洗练",
        WashContent: "当前洗练的词条中包含珍贵词条，确认要洗练吗，洗练会失去未框选的词条",
    },
       CreateRole: {
        title: "Tạo nhân vật",
        name_placeholder: "Nhập tên nhân vật...",
        NameEmpty: "Vui lòng nhập tên nhân vật!",
        Male: "Nam",
        Female: "Nữ",
        Ok: "Xác nhận",
        Cancel: "Huỷ",
        RandomName: "Ngẫu nhiên"
    },
    Trial: {
        TabTrialTower: "试炼之塔",
        TabGuMoTower: "锢魔之塔",
        TrialTower: {
            LayerShow: "第{0}层",
            RecordLayerShow: "本期最高层数：{0}层",
            RecordRankShow: "本期试炼排名：{0}",
            RecordRankShowNone: "本期试炼排名：暂无排名",
            RewardRankLater: "{0}及以后",
            RankLayerShow: "{0}层",
            ItemShiLianDescShow: "每级提高{0}{1}",
            ItemShiLianDescShow2: "{0}级提高<color=#" + COLORSTR.Yellow5 + ">{1}</color>{2}",
            UseLockTips: "当前格子未解锁",
            BagEmptyTips: "无法装备空物品",
            LockTips: "需要{0}个{1}才能解锁",
            TimeShow: "距试炼结束：{0}",
            SpoilNewTips: "获得新的战利品：{0}",
            SpoilUpTips: "战利品：{0}，已提升到{1}级",
            LevelNameShow: "第{0}关",
        },
        GuMoTower: {
            LayerShow: "第{0}层",
            ConditionFont: "条件{0}：{1}",
            StarReward: "{0}星",
            DayReward0: "暂未挑战锢魔之塔，当天挑战后次日0点才可领取",
            DayRewardGet: "领取",
            DayRewardGeted: "已领取",
            RewardDescShow: "{0}关\n可领取",
            RewardConditionShow: "当天挑战后次日<color=#" + COLORSTR.Red5 + ">0点</color>才可领取",
        },
        RankReward: "排名奖励预览",
        RankRewardTip: "试炼之塔根据每周排名结算奖励，以邮件形式发放",
    },
    Fish: {
        MainName: "考 古",
        MainTitle: "考 古",
        TabToolUpLevel: "强 化",
        TabToolUpGrade: "突 破",
        BoxTypeShows: {
            [0]: "远古化石",
            [1]: "珍稀矿石",
            [2]: "遗迹宝物",
            [3]: "地底生物",
            [4]: "收藏品",
        },
        WaBaoFailReason: {
            [-3]: "很遗憾，这里空无一物",
            [-2]: "地质太硬，强度无法突破",
            [-1]: "宝物被人抢走啦",
        },
        FishMain: {
            OrderProgressShow: "{0}/{1}"
        },
        FishOrder: {
            OrderProgressShow: "{0}/{1}",
            TimeShow: "<outline color=#" + COLORSTR.Green2 + " width=2><color=#" + COLORSTR.Green1 + ">{0}</color></outline> <outline color=#" + COLORSTR.Yellow2 + " width=2><color=#" + COLORSTR.Yellow1 + ">后自动刷新订单</color></outline>",
            DescShow: "获得{0}个{1}",
            GetTips: "获得{0} x{1}",
        },
        FishMap: {
            MapGo: "前往",
            MapLock: "暂未解锁",
            MapUnLock: "解锁",
            ConditionShow: {
                [0]: "等级达到<color=#" + COLORSTR.Blue2 + ">{0}</color>级",
                [1]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个化石",
                [2]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个矿石",
                [3]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个宝物",
                [4]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个生物",
                [5]: "冒险通关<color=#" + COLORSTR.Blue2 + ">{0}</color>关",
            },
            ProgressShow: "<color=#{0}>{1}</color>/{2}",
            ArrowNextLock: "前置场景未解锁",
        },
        FishHandbook: {
            ProgressShow: "已解锁：{0}/{1}"
        },
        FishCollectReward: {
            AttrShow: "{0}：+{1}",
            CurLevel: "等级：{0}",
            CostNumEnough: "<color=#" + COLORSTR.Green3 + ">{0}/{1}</color>",
            CostNumNotEnough: "<color=#" + COLORSTR.Red1 + ">{0}</color><color=#" + COLORSTR.Yellow2 + ">/{1}</color>",
            TitleShows: {
                [0]: "收藏品",
                [1]: "海底洞穴",
                [2]: "森林洞穴",
                [3]: "回声洞穴",
            },
            UpSucc: "升级成功",
            ActiveSucc: "激活成功",
            BtnActive: "激活",
            BtnActived: "已激活",
        },
        FishSetting: {
            QuaDesc: {
                [0]: "优秀及以上",
                [1]: "精良及以上",
                [2]: "稀有及以上",
                [3]: "史诗及以上",
                [4]: "传奇及以上",
                [5]: "天赐及以上",
                [6]: "神铸及以上",
            },
            StopSucc: "停止成功",
        },
        FishGet: {
            AttrShow: "{0}：+{1}"
        },
        FishBox: {
            AttrShow: "{0}：+{1}",
            NextTips: "展柜升级到{0}级解锁"
        },
        FishBoxUp: {
            LevelCur: "当前等级：{0}",
            LevelNext: "下一等级：{0}",
            unit: "个",
            AttrShows: {
                [1]: "远古化石：",
                [2]: "珍稀矿石：",
                [3]: "遗迹宝物：",
                [4]: "地底生物：",
            },
            NeddTime: "时间：",
            TimeShow: "<outline color=#" + COLORSTR.Yellow2 + " width=2><color=#" + COLORSTR.Yellow1 + ">{0}</color></outline>",
            CanUpTips: "已达到升级条件",
        },
        FishToolUp: {
            LevelShow: "{0}阶{1}级",
            TaskUpNo: "未达到当前等级上限\n无法进行突破",
            ConditionShow: {
                [0]: "等级达到<color=#" + COLORSTR.Blue2 + ">{0}</color>级",
                [1]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个远古化石",
                [2]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个珍稀矿石",
                [3]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个遗迹宝物",
                [4]: "挖到<color=#" + COLORSTR.Blue2 + ">{0}</color>个地底生物",
            },
            UpLevelSucc: "强化成功",
            UpLevelFail: "突破到{0}阶可继续强化",
            UpGradeSucc: "突破成功",
        },
        FishInfo: {
            RecordShow: "历史大小：{0}厘米"
        },
        WaBaoingTips: "挖宝中,请稍后!",
        ItemTypeName: {
            [0]: "矿物大小",
            [1]: "幸运",
            [2]: "强度",
            [3]: "防盗",
            [4]: "售卖价格",
        },
    },
    ShenQi: {
        MainName: "神 器",
        MainTitle: "神 器",
        ShenQiMain: {
            BtnDrawFree: "免费{0}次",
            TimeShow: `<outline color=#${COLORSTR.Yellow2} width=${2}><color=#${COLORSTR.Green4}>{1}</color>后获得<color=#${COLORSTR.Green4}>{0}</color>次免费刷新机会</outline>`,
            DrawingTips: "抽奖中",
        },
        ShenQiRecord: {
            TitleShow: "查看记录",
            EnergyNum: "神器能量x{0}",
            ItemName: "获得{0}",
            ItemNames: {
                [2]: "超级翻倍",
                [3]: "神器碎片",
            }
        },
        ShenQiInfo: {
            NumShow: "碎片：{0}/{1}",
            Max: "已满级",
            NotActive: "未激活",
            NotActiveTips: "暂未激活，无法穿戴",
            WearingTips: "神器{0}已穿戴",
            BtnWear: "穿戴",
            BtnWeard: "已穿戴",
        },
        ShenQiEnergy: {
            DescShow: "神器能量不足，是否用 <color=#" + COLORSTR.Blue2 + ">{0}</color> 个万能碎片代替升级"
        },
        ShenQiAttr: {
            QuaLevel: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>绿色品质：Lv.{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>蓝色品质：Lv.{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>橙色品质：Lv.{0}</outline>`,
            },
            NextLevel0: "未激活",
            NextLevel: "再升{0}级即可获得属性提升",
            DescShow: {
                [2]: `绿色品质神器每提升{0}级,{1}`,
                [3]: `蓝色品质神器每提升{0}级,{1}`,
                [6]: `橙色品质神器每提升{0}级,{1}`,
            },
        },
        ShenQiEnter: {
            QuaLevel: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>Lv.{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>Lv.{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>Lv.{0}</outline>`,
            },
            AttrShow: {
                [2]: `<outline color=#${COLORSTR.Green2} width=${2}>{0}</outline>`,
                [3]: `<outline color=#${COLORSTR.Blue3} width=${2}>{0}</outline>`,
                [6]: `<outline color=#${COLORSTR.Yellow2} width=${2}>{0}</outline>`,
            },
            NotActive: "未激活",
        }
    },
    Guild: {
        TabGuild: "骑士团",
        TabGuildHelp: "互助",
        TabGuildInfo: "团员",

        GuildTrain: {
            TabTrain: "骑士锻炼",
            TabTrainPrimary: "普通",
            TabTrainAdvanced: "高级",

            LevelShow: `锻炼总等级：<color=#${COLORSTR.Yellow9}>{0}</color>`,
            PartNames: ["头部锻炼", "手部锻炼", "身体锻炼", "胳膊锻炼", "腿部锻炼", "脚部锻炼"],
            ConditionShow: [`普通锻炼<color=#${COLORSTR.Red2}>{0}级</color>解锁`, `高级锻炼<color=#${COLORSTR.Red2}>{0}级</color>解锁`],
            ResetTips: "是否确认消耗{0}{1}重置所有\n改造？重置后将清空改造等级，\n并返还全部资源",

            AdvancedOpenTips: "普通锻炼{0}级开放",
        },
        GuildCreate: {
            NameNumTips1: "骑士团名长度小于2，创建失败",
            NameNumTips2: "骑士团名长度大于12，创建失败",
            CreateTips: "确认要创建骑士团吗?",
        },
        GuildInfo: {
            NoticeShowEmpty: "团长很懒，还没有编辑公告！",
            BtnOpers: ["退出", "驱逐", "任命", "降职", "转让", "转让"],
            DismissTips: "确认要解散骑士团吗?",
        },
        GuildBoss: {
            ProgressValShow: "当前剩余血量:{0}%",
            TimesShow: "今日剩余挑战次数：{0}",
            FightTips: "是否确认消耗{0}{1}挑战一次BOSS？",
            BtnGet: "领取",
            BtnGeted: "已领取",
        },
        GuildHelp: {
            ContentShow: [
                "",
                "玩家\"{0}\"加入骑士团",
                "玩家\"{0}\"退出骑士团",
                "玩家\"{0}\"将团长转让给\"{1}\"",
                "玩家\"{0}\"将副团长转让给\"{1}\"",
                "",
                "玩家\"{0}\"任命\"{1}\"为副团长",
            ],
            ProgressValShow: `<color=#${COLORSTR.Green4}>{0}</color> / {1}`,
        },

        NameShow: "团名：{0}",
        IdShow: "ID：{0}",
        NumShow: "团员：<color=#{2}>{0}</color>/{1}",

        PositionShow: [`<color=#${COLORSTR.Yellow9}>团长</color>`, `<color=#${COLORSTR.Blue4}>副团长</color>`, "团员"]
    },
    Block: {
        MainTitle: "积 木",
        BlockModel: {
            EmptyTips: "请先获取图纸",
            QuaShow: "{0}色品质"
        },
        BlockFill: {
            AttrShow: "{0}  +{1}",
            Wu: "无",
            Block0Tips: "当前模型暂未镶嵌",
            BtnWear: "装 备",
            BtnWearing: "装备中",
        },
        BlockCompose: {
            SelNum: "请选中3块积木进行合成",
            SelSame: "请选择相同品质的积木进行合成",
            SelMap: "请选择未镶嵌的积木进行合成",
            MaxMap: "当前积木已达最高等级，无法继续合成",
            ComposeTips: "确定要进行合成吗？当前的合\n成成功率为{0}%，合成\n失败将随机损失一个积木",
            FailTips: "合成失败",
        },
        BlockAchieve: {
            TitleShow: "同时拼满{0}个模型",
            ProgressShow: "({0}/{1})",
            AttrShow: "{0}：+{1}",
        },

        QuaDesc: {
            [0]: "优秀",
            [1]: "精良",
            [2]: "稀有",
            [3]: "史诗",
            // [4]: "传奇",
            [5]: "天赐",
            [6]: "神铸",
        },
        QuaColor: {
            [1]: "红色",
            [2]: "黄色",
            [3]: "蓝色",
            [4]: "绿色",
        },
        All: "全部"
    },
    NewServerCompetition: {
        RankNames: {
            [0]: "竞技场",
            [1]: "法阵魂石",
            [2]: "角色等级",
            [3]: "锢魔之塔",
            [4]: "冒险",
            [5]: "宠物",
            [6]: "法阵",
            [7]: "星图",
            [8]: "坐骑",
            [9]: "时装",
        },
        RankVal: {
            [0]: `< color=#${COLORSTR.Yellow1} > 排名：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [1]: `< color=#${COLORSTR.Yellow1} > 总等级：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [2]: `< color=#${COLORSTR.Yellow1} > 等级：< /color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [3]: `< color=#${COLORSTR.Yellow1}> 星级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [4]: `< color=#${COLORSTR.Yellow1}> 关卡：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [5]: `< color=#${COLORSTR.Yellow1}> 宝石总等级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [6]: `< color=#${COLORSTR.Yellow1}> 总等级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [7]: `< color=#${COLORSTR.Yellow1}> 总等级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [8]: `< color=#${COLORSTR.Yellow1}> 觉醒总等级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
            [9]: `< color=#${COLORSTR.Yellow1}> 总等级：</color><color=#${COLORSTR.Yellow3}>{0}</color > `,
        },
        RankEmptyVal: {
            [0]: `< color=#${COLORSTR.Red7}> 需达排名：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [1]: `< color=#${COLORSTR.Red7}> 需达总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [2]: `< color=#${COLORSTR.Red7}> 需达等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [3]: `< color=#${COLORSTR.Red7}> 需达星级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [4]: `< color=#${COLORSTR.Red7}> 需达关卡：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [5]: `< color=#${COLORSTR.Red7}> 需达宝石总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [6]: `< color=#${COLORSTR.Red7}> 需达总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [7]: `< color=#${COLORSTR.Red7}> 需达总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [8]: `< color=#${COLORSTR.Red7}> 需达觉醒总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
            [9]: `< color=#${COLORSTR.Red7}> 需达总等级：</color><color=#${COLORSTR.Red7}>{0}</color > `,
        },
        // RewardVal: {
        //     [0]: `排名：{ 0 } `,
        //     [1]: `总等级：{ 0 } `,
        //     [2]: `等级：{ 0 } `,
        //     [3]: `星级：{ 0 } `,
        //     [4]: `关卡：{ 0 } `,
        //     [5]: `宝石总等级：{ 0 } `,
        //     [6]: `总等级：{ 0 } `,
        //     [7]: `总等级：{ 0 } `,
        //     [8]: `觉醒总等级：{ 0 } `,
        //     [9]: `总等级：{ 0 } `,
        // },
        RewardVal: {
            [0]: `排名：{0} `,
            [1]: `排名：{0} `,
            [2]: `排名：{0} `,
            [3]: `排名：{0} `,
            [4]: `排名：{0} `,
            [5]: `排名：{0} `,
            [6]: `排名：{0} `,
            [7]: `排名：{0} `,
            [8]: `排名：{0} `,
            [9]: `排名：{0} `,
        },
        NoRank: "未上榜",
        TimeShow: "比拼剩余时间：{0}",
        ActEnd: "已结算",
        OpenDay: "{0}日后开启",
    },
    AdEquity: {
        DescShow: [
            { desc_show: `< color=#${COLORSTR.Green3}> 免费跳过 < /color>宝箱升级加速广告` },
            { desc_show: `<color=#${COLORSTR.Green3}>免费跳过</color>藏品升级加速广告` },
            { desc_show: `<color=#${COLORSTR.Green3}>免费跳过</color>骑士之证奖励广告` },
            { desc_show: `<color=#${COLORSTR.Green3}>免费跳过</color>每日福利钻石广告` },
            { desc_show: `<color=#${COLORSTR.Green3}>免费跳过</color>福利活动奖励广告` },
        ],
        productName: "广告权益",
    },
    KnightCard: {
        BtnBuyedShow: "已购买",
        BtnGetShow: "领取",
        BtnGetedShow: "已领取",
        GetedTips: "今日已领取",
        GetNotTips: "请先领取前一个奖励",
        TimeShow: `剩余时间：<color=#${COLORSTR.Green4}>{0}</color>`,
    },
    DataHelper: {
        DaXie: ["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万"],
        FanTi: ["零", "壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾", "佰", "仟", "萬"],
    },
    Battle: {
        tip: "加载失败",
        round: "第{0}回合",
        loading: "战斗加载中...",
    },
    Angel: {
        MainTitle: "法 阵",
        level_add: "等级加成",
        grade_add: "进阶加成",
        tip: "完成主线任务激活法阵魂石",
        jie: "阶",
        tip2: "激活后才能幻化",
        tip3: "幻化成功",
        Angel: "法阵",
        HuanHua: "幻化",
        HuanHuaTip: "已取消法阵幻化",
        Title: "法 阵",
    },
    Arena: {
        day_reward: "每日排名奖励",
        day_reward_tip: "竞技场根据排名，每天24时通过邮件发放奖励",
        week_reward: "每周排名奖励",
        week_reward_tip: "竞技场根据排名，每周日24时通过邮件发放奖励",
        RankScoreShow: "积分：{0}",
        rank_title: "本周排名",
        result_desc: [
            "挑战成功：    +{0}",
            "挑战失败：    -{0}",
            "防御成功",
            "防御失败：    -{0}",
            "复仇成功：    +{0}",
        ],
        result_desc2: [
            "挑战成功：{0} +{1}",
            "挑战失败：{0} {1}",
            "防御成功",
            "防御失败：{0} {1}",
            "复仇成功：{0} +{1}",
        ],
        challenged: "本周累计：",
        cur_rank: "当前排名：",
        cur_score: "积分：",
        cap: "战力：",
        score: "积分：",
        tip: "挑战次数不足",
        hour_before: "小时",
        min_before: "分钟前",
        arena: "竞 技",
        tip2: "当前玩家已屏蔽角色信息",
        score_desc: "竞技场积分：",
        no_rank: "未上榜",
        rank: "第{0}名",
        NoPet: "暂无宠物上阵",
    },
    StarMap: {
        MainTitle: "星 图",
        SuperStarTitle: "天赋树",
        Grade: "阶",
        TypeName: ["主 角", "宠 物"],
        GradeLock: "激活上一阶所有天赋孔后开启",
        LevelMax: "该天赋孔已满级",
        PointOper: ["激活", "升级"],
        LinkError: "相邻的天赋孔未激活",
        LinkLevelError: "前置天赋孔达到{0}级即可升级",
        ItemLack: "升级所需物品不足",
        Cost: "消耗",
        ResetTitle: "重置",
        ResetItemLack: "重置所需物品不足",
        StarPointMax: "该天赋孔已达最大等级",
        PointUpLevelError: "所有天赋孔达到{0}级即可提升下一级",
        MaxLevel: "当前星系已满级",
    },
    StarMapSuperNew: {
        tabTitles: [null, "攻击", "防御", "生命", "速度"],
        activeTIp: "需先激活前置天赋点",
    },
    Pet: {
        pet: "宠 物",
        PetInfo: "宠物信息",
        PetLevelUp: "宠物升级",
        PetAdvence: "宠物觉醒",
        PetSkill: "宠物技能",
        last_pet_tip: "禁止放生最后一只宠物",
        exp: "经验*{0}",
        advence_order: "觉醒·{0}阶",
        select_pet_tip: "请选择一只宠物",
        no_pet_tip: "还没有获得宠物",
        pet_embattle_succ: "宠物上阵成功",
        pet_outbattle_succ: "宠物下阵成功",
        pet_changebattle_succ: "宠物替换成功",
        pet_changepos_succ: "宠物换位成功",
        pet_outbattle_desc: "{0}级解锁",
        grade_level: "{0}阶{1}级",
        lock: "未解锁",
        select_skill_tip: "请选择一个技能书",
        cost_tip: "锁定{0}个技能，每次学技能时外消耗{1}",
        pet_skill_tab: ["初级技能书", "高级技能书", "顶级技能书"],
        no_select_skill: "没有选中的技能书",
        return_tip: "宠物已成功放生",
        AttrShow: "{0}:",
        ts_gem_name: "{0}级宠物特殊宝石",
        CostPetGrade: "{0}阶本体宠",
        AdvenceTip: "是否确定消耗<color=#" + COLORSTR.Green3 + ">【+{0}】进行觉醒，觉醒之后<color=#" + COLORSTR.Green3 + ">【+{1}】</color>所佩戴的宝石将会拆下，技能书和经验将不会返还",
        AdvenceTip2: "是否确定进行觉醒，觉醒之后<color=#" + COLORSTR.Green3 + ">【+{0}】</color>所佩戴的宝石将会拆下，技能书和经验将不会返还",
        WashTip: "洗练会获得新的<color=#" + COLORSTR.Yellow3 + ">词缀</color>，达到上限时洗练会<color=#" + COLORSTR.Yellow3 + ">更换词缀</color>，勾选后\n的词缀不会消失，当前词缀上限为当前宝石等级",
        PetSkillMap: {
            tab: ["初级技能", "高级技能", "顶级技能"],
        },
        PetSkillCover: "选中技能等级高于学习技能，确认覆盖吗",
        GemNotUp: "材料不足，无法升级",
        GemSet: "宝石镶嵌",
        Tip: "请前往活动获取宠物宝石",
        GemStore: "宝石仓库",
        GemWash: "宝石洗练",
        GemUp: "宝石升级",
        GemMaxTip: "等级已满",
        GemUpTip: "宝石升级会消耗<color=#" + COLORSTR.Yellow3 + ">1颗同等级宝石</color>，已经装备的宝石不受影响",
        OneKeyTip: "请选择一键提升的材料",
        CanUp: "可升级",
        NoItems: "材料不足",
        UpTip: "需要{0}颗{1}（{2}）",
        UpTip2: "仍需要{0}颗{1}才能升级（{2}）",
        EvolTitle: "宠物进化",
        NoItemsForEvol: "材料不足，无法进化",
        downTip: "下阵",
        upTip3: "上阵",
        EmIndexTip: "位置 {0}",
        RateTitle: "奖池概率",
        RateTag: ["基础", "高级", "豪华"],
        SkillUnlockTip: "请先解锁技能格",
        SkillUnlockForamt: "是否花费{0}{1} 解锁宠物技能格?",
    },
    Escort: {
        Name: "护送",
        Title1: "护航船只",
        Title2: "排名奖励预览",
        Title3: "护航记录",
        Title4: "拦截记录",
        Title5: "排 行",
        Title6: "品质提升",
        Title7: "拦截",
        //Level:"<color=#{0}>{1}级</color>",
        Level: "{0}级",
        Time: "护航:{0}分钟",
        TabbarName1: "劫掠排行榜",
        TabbarName2: "积分排行榜",
        RankNum: "{0}-{1}",
        RankNum2: "{0}及以后",
        BoatName: "{0}级商船",
        MaxLevel: "已满级",
        MaxTip: "船只品质已满级",
        QuaNoChange: "船只品质升级失败",
        MaxCount: "护航次数已满",
        TimeDesc: "{0}年{1}月{2}日",
        ShengYu1: "剩余拦截次数：{0}/{1}",
        Count: "{0}/{1}",
        ShengYu2: "剩余次数：{0}",
        JiFen: "积分：{0}",
        Time2: "{0:D2}:{1:D2}",
        EscortStart: "开始护航{0}级商船",
        MySelf: "不能拦截自己的船",
        ItemDesc: "{0}x{1}",
        InterTip: "超出拦截次数，该船只无法被拦截",
        EscortTip: "已经有船只出海，完成当前护航后才能再次出发",
        HelpTip: "救援成功",
        GhostTimeDesc: "幽灵船逃离：",
    },
    GemAtelier: {
        MainTitle: "宝 石",
        Title: "宝 石",
        InsetTitle: "宝石镶嵌",
        UpGradeTitle: "宝石升级",
        TagName: ["普通图纸", "特殊图纸"],
        LvShow: "Lv.",
        LackSpError: "{0}可以通过{1}获得",
        LevelError: "{0}可以通过{1}获得",
        GemTagError: "该类宝石未获取",
        LackItemError: "材料不足",
        LevelGradeError: "等级与目标宝石不同",
        LevelShow: "等级：",
        DrawUnAct: "图纸属性尚未激活",
        FullDrawTips: "图纸宝石最多放置6个",
        MixTitle: "升级",
        DrawUpDateSuccess: "宝石图纸升级成功，已提升到{0}级",
        PicUp: "升级完成",
        ChangeTarget: "可替换宝石",
        ChangeGem: "宝石转换",
        GemUpEmpty: "请先选择升级目标",
        ChangeEmpty: "请先选择转换目标",
        GemChangeEmpty: "请先选择被转换目标",
        GemOneKeyUp: "一键升级",
        GemUpTip: "宝石升级会消耗<color=#" + COLORSTR.Yellow3 + ">3颗同等级宝石</color>",
        GemUpNeed: "需要{0}颗{1}级宝石",
        GemDrawTitle: "需要宝石",
        OneKeyGemLack: "一键升级所需宝石不足",
        OneKeyLevelLow: "一键升级需要1级以上图纸",
        OneKeyGemLackNeed: "缺少{0}个{1}",
    },
    CommodityGuildItem: {
        Yuanjia: "原价：{0}",
        LimitBuy: ["总限购：", "日限购："],
        JinDu: "{0}/{1}",
        Zhe: "{0}折",
        Cost: "{0}元",
        StarZhe: "{0}至{1}折",
    },
    CaveLoot: {
        Zhe: "{0}折",
        BaoDiDesc: "再探<color=#" + COLORSTR.Yellow3 + ">{0}</color>次必得珍稀道具",
        UseNum: "{0}/{1}",
        GaiLu: "{0}%",
        Free: "免费",
        XianGou: ["日限购：", "活动限购："],
        RechargeDesc: "累计充值{0}元",
        RechargeNum: "<color=#" + COLORSTR.Green3 + ">{0}</color>",
        RechargeNum1: "<color=#" + COLORSTR.Yellow5 + ">{0}</color>",
        RechargeNum2: "已累计充值<color=#" + COLORSTR.Yellow5 + ">{0}</color>元",

    },
    BoxManor: {
        xiangou: ["限购{0}次", "日限购{0}次"],
    },
    IntegralTurntable: {
        UseNum: "{0}/{1}",
        must: `抽<color=#${COLORSTR.Yellow3}>{0}</color>次必得`,
        current: `当前积分：<color=#${COLORSTR.Yellow1}>{0}</color>`,
        probability: "转盘概率",
        cherish: "珍惜道具",
        rests: "其他其他",
        source: "积分来源",
        consume: "消耗以下道具获得积分",
        score: "{0}积分/个",
        DrawingTips: "抽奖中",
        onScore: "积分不足",
        GaiLu: "{0}%",
    },
    ExclusiveGift: {
        Purchase: `仅限购{0}次，价值<color=#${COLORSTR.Yellow9}>{1}</color>元！`,
        Price: "¥{0}",
    },
    ClothShop: {
        ClothShopTitle: ["时装", "坐骑", "法阵", "宠物"],
        Price: "¥{0}",
        QuaDesc: {
            [3]: "史诗",
            [4]: "传说",
            [5]: "天赐",
            [6]: "神铸",
            [7]: "超凡",
        },
    },
    Recharge: {
        noOpen: "充值未开放",
        Diamond: "钻石",
        GoldType: [
            "¥",
            "$",
            "NT$",
            "₩",
            "₫"
        ],
        ItemBuyDesc: "是否消耗{0}个万能卡",
        ItemNum: "万能卡：{0}个",
    },
    LoopMine: {
        MainTitle: "夺宝",
        Title: "夺 宝",
        BtnTitle: "夺宝{0}次",
        TagName: ["初级夺宝", "高级夺宝"],
        ItemLackError: "道具不足",
        ItemLast: "剩余:{0}次",
        RewardGot: "该奖励已获得",
        RewardLackNum: "幸运值不足",
        RecordTitle: "夺宝记录",
        RecordCell: "{0}获得了{1}",
        NeedReflush: "奖池已清空，请刷新",
    },
    MainOther: {
        shop: "商城",
        manual: "进阶手册",
        mystery_shop: "神秘商店",
        friend_rank: "好友排行",
        knight_card: "骑士之证",
        guild: "骑士团",
        item_recycling: "物品回收",
    },
    InviteFriends: {
        InviteDesc: "邀请<color=#" + COLORSTR.Green3 + ">{0}</color>个好友",
    },
    Fashion: {
        Title: "时 装",
        MainTitle: "时 装",
        TabName: ["头盔", "武器", "铠甲", "护盾"],
        Title2: ["激活", "升星", "已达上限"],
        CostDesc: ["激活消耗", "升级消耗"],
        FashionMax: "该时装已达最大等级",
        LevelTip: "时装未激活",
        HuanHuaSuccess: "穿戴成功",
        HuanHuaCancel: "穿戴已取消",
        ActiveTips: "确定要花费<color=#" + COLORSTR.Yellow5 + ">{0}</color>{1}激活\n<color=#" + COLORSTR.Green3 + ">[{2}]</color>吗?"
    },
    OpenServer: {
        BoxOpenType: ["{0}", "开启宝箱{0}个", "宝箱等级达到{0}"],
        LimitError: "领取条件未达成",
        TimeLimit: "活动剩余时间",
        NeoServerNeedError: "购买所需道具不足",
        NeoServerTimeError: "购买次数已用完",
        NeoServerLimitType: ["", "限购：", "今日限购："],
        SevensDayShow: "第{0}天",
        SevensDaysDaysError: "请明日再来领取奖励！",
        SevensDaysDaysEndError: "所有奖励已领取",
        SevensDaysDone: "已领取",
        SevensDaysWait: "领取",
        NeoShopOffShow: "折",
        NeoShopFLushTime: "{0}后免费刷新",
        NeoShopFlushError: "刷新所需的货币不足",
        NeoShopTimesError: "该商品已达本次刷新的购买上限",
        NeoShopbuyError: "购买该商品所需的货币不足",
        NeoShopbuyDiaError: "钻石不足，请前往充值",
        Title: ["七日登录", "开箱大吉", "新服特惠", "外观商店"],
        NeoShopFlushFree: "免费刷新",
        NeoShopFlush: "刷新",
        NeoShopSellDone: "已售罄",
        NeoShopPriceLack: "不足",
        NoteEnoughLevel: "等级不足，升级之后再来体验",
        BoxNotEnoughLevel: "宝箱等级不足，升级之后再来体验",
        ItemNotEnough: "夺宝令数量不足",
        ShopDayFlush: "今日刷新次数：",
        ShopDayFlushEnd: "今日刷新次数已用完",
    },
    FightAccount: {
        Scoure: [`{0}<color=#${COLORSTR.Green1}>（+{1}）</color>`, `{0}<color=${COLORSTR.Red1}>（{1}）</color>`],
    },
    LeiChong: {
        WeiDaCheng: "您还未达到领取目标哦！",
        Desc: "累计充值{0}元奖励",
        NextTip: "{0}元",
        ValueTip: "价值 ¥{0}",
        ValueTip2: "价值 {0}",
        BtnTitle: "¥{0}",
        BtnTitle2: "¥ {0}",
        BtnTitle3: "待领取",
        TimeStr: `<color=#${COLORSTR.Green4}>{0}</color>分<color=#${COLORSTR.Green4}>{1}</color>秒`,
    },
    LuckyGift: {
        LuckyGift: "幸运礼遇",
        value: "价值",
    },
    MonthlyCard: {
        UnLockGet: "解锁立得",
        DailyGet: "每日登录可领取",
        Tip: "今日已领取",
        MonthlyCard: "月卡",
        FishSpeed2: "挖宝速度加快2倍",
    },
    FunOpen: {
        LevelTip: "角色等级到达{0}级后开启",
        TaskTip: "任务未完成，完成之后再来体验",
        OpenTip: "功能已开启"
    },
    Task: {
        Finsh: "已完成",
    },
    GetWay: {
        LevelShow: "使用等级:"
    },
    Shop: {
        limit_desc: [
            "",
            "每日限购",
            "每周限购",
            "永久限购",
        ],
        Box: "魔法宝箱",
    },
    FastBuy: {
        FastBuy: "快捷购买",
        tip: "数量不能为0",
        desc: "是否快捷购买{0}个{1}",
    },
    CommonGet: {
        AttrShow: "{0}：               +{1}",
        Split: ["      ", "      ", "      ", "      ", "      ", "", "      ", "      ", "      ", "      " //10
            , "      ", "", "", "", "", "", "", ""],
    },
    CDKeyExchange: {
        RetCode: [
            "兑换成功，奖励已发送到邮箱",
            "兑换码错误",
            "不能重复使用",
            "区服错误",
            "兑换码已过期",
            "兑换码已被使用",
            "请达到指定等级后兑换",
            "其他错误",
            "兑换码已失效",
            "累充金额不足",
        ],
        EmptyHint: "请输入兑换码",
        OtherError: "未知错误[%d]",
    },
    TodayShare: {
        Status: "今日分享奖励：{0}/1",
        BtnStatus: ["分享", "直接领取", "已领取", "领取"],
        FetchDone: "您今天已领取分享奖励",
    },
    ScoreFund: {
        title: '评分达到（{0}/{1}）',
        ScoreFund: "评分基金",
    },
    Inscription: {
        MainTitle: "铭 文",
        ResolveTitle: "铭文分解",
        SelectTitle: "选择铭文",
        AtlasTitle: "铭文图鉴",
        UnLockTips: "通过铭文之塔{0}层\n解锁铭文孔{1}位",
        UnLockPopTips: "需通关铭文之塔{0}层解锁",
        UpGradeLack: "材料不足",
        AtlasCoreItemTitle: "核心铭文",
        AtlasNomalDefaultTitle: "默认解锁",
        AtlasNomalTowerTitle: "铭文之塔{0}层解锁",
        ResolveEmpty: "未选择铭文",
        NeedEquiped: "暂未穿戴铭文",
        BtnExchange: "替换",
        BtnEquip: "镶嵌",
        BtnSExchange: "替 换",
        BtnSEquip: "镶 嵌",
        SkillStart: "技能效果：",
        DetailCurShow: ["属性加成", "技能效果："],
        BtnUp: "升级",
        BtnUpMax: "已满级",
        Tower: {
            LayerShow: "第{0}层",
            DescShow: `通关 <color=#${COLORSTR.White}>{0}关</color> 后获得`,
            DayRewardGet: "领取",
            DayRewardGeted: "已领取",
            DayReward0Tips: "暂未挑战铭文之塔，挑战后即可领取奖励",
        },
        Turntable: {
            // DescShow1: `单次抽奖耗费<color=#${COLORSTR.Green4}>{0}{1}，</color>十连抽每次消耗<color=#${COLORSTR.Green4}>{0}{2}</color>`,
            DescShow1: `每日3次广告免费抽取次数`,
            DescShow2: `抽中大奖可获得随机奖励，并可获得本轮剩余全部\n奖励进入下一轮`,
            RoundShow: "当前轮数：第{0}轮",
            NumShow: "剩余次数：<color=#{0}>{1}</color>次",
            DrawingTips: "抽奖中",
            DrawNumTips: "{0}不足",
            BtnDraw1: "抽取1次",
            BtnDraw5: "抽取5次",
            FreeTimes: "今日免费剩{0}次",
            AdTips: "之后可以再次免费获取",
            BtnFree: "免费获取",
        },
        MainTag: ["铭文之心", "铭文图鉴", "铭文分解", "铭文宝箱"],
        BtnEmptyAttr: "请安装铭文后再来查看",
    },
    AngelFes: {
        Title: "法阵庆典",
        TagName: ["法阵升级", "圣装升级", "超值折扣"],
        TaskUnComplete: "尚未完成",
        BtnComplete: "领取",
        BtnDone: "已领取",
        BtnUnComplete: "暂未达成",
        GiftLimit: ["{0}", "{0}", "日限购：{0}", "限购：{0}"],
        Offset: "折",
        LimitBuyFull: "购买次数已用完",
    },
    AffordPresent: {
        NumShow: "数量：",
        Days: "第{0}天",
        BuyWait: "领取时间未到",
    },
    adv: {
        daily: "观看视频成功，获得{0}钻石",
        speed: "观看视频成功，升级时间减少{0}分钟",
        inscription_turntable: "观看视频成功，获得{0}次铭文抽奖机会",
        knight_card: "观看视频成功，获得{0}{0}",
        weekend_rechagre: "观看视频成功,增加{0}额度",
        canvas_ling: "观看视频成功,送夺宝令",
        level_fun: "观看视频成功,双倍领取",
        box_fun: "观看视频成功,双倍领取",
        today_share: "观看视频成功，双倍奖励",
        draw: "观看视频任务完成,开始抽奖",
        territory_refresh: "观看视频成功,刷新所有资源",
    },
    StarMapFes: {
        Title: "星图庆典",
        TagName: ["主角星图", "宠物星图", "星图提升"],
        TaskUnComplete: "尚未完成",
        BtnComplete: "领取",
        BtnDone: "已领取",
        BtnUnComplete: "暂未达成",
        GiftLimit: ["{0}", "{0}", "日限购：{0}", "限购：{0}"],
        Offset: "折",
        LimitBuyFull: "购买次数已用完",
        BtnFree: "免费",
    },
    TrailChengJiu: {
        JingJieCost: "解锁进阶  {0}"
    },
    ContinuePresent: {
        RatePreView: "奖励预览",
        TaskAND: " 或 ",
        TaksShow: ["充值{0}", "邀请好友{0}"],
        DayShow: "第{0}天",
        BigCountShow: "{0}天任务已完成，再完成{1}天即可领取大奖",
        BigCountPro: "进度：{0}/{1}",
        UnCompleteTips: "任务未完成，不可领取"
    },
    FriendsRank: {
        Title: "好友排行"
    },
    WeekHaoLi: {
        XianGou: ["{0}", "总限购：{0}", "每日限购：{0}"],
        Cost: "¥ {0}",
        TimeLimit: "活动剩余时间：",
        // TimeStr5: "<color=#${COLORSTR.Yellow1}>{0}</color>天<color=#${COLORSTR.Yellow1}>{1}</color>时",
        TimeStr5: `<color=#${COLORSTR.Yellow3}>{0}</color>天<color=#${COLORSTR.Yellow3}>{1}</color>时`,
    },
    Enchant: {
        Title: "附 魔",
        IsActive: ["已激活{0}/{1}", "未激活"],
        State: ["激活中...", "未激活"],
        CancelEnchant: "取消后已经消耗的材料不返还，确认放弃现有时间吗？",
        StillEnchant: "附魔激活数量已达上限，本次激活无法获得属性加成，是否继续",
        EnchantLevel: "附魔等级{0}/{1}",
        ShowBuffDesc: "{0}:{1}%",
        ShowBuffDesc2: "{0}%",
        NeedNUm: "<color=#{0}>{1}</color>/{2} ",
        NoNum: "未选择附魔材料。",
    },
    PeakArena: {
        EnterName: ["竞技场", "跨服竞技场"],
        NeoPointShow: "积分：",
        PointShow: "分",
        RankTag: ["今日排名", "本周排名"],
        DailyTitle: "本日排名",
        WeeklyTitle: "本周排名",
        RankTitle: "排名",
        RecordTitle: "战斗记录",
        TimePlus: "前",
        LevelShow: "lv.",
        BtnRevenge: "复仇",
        RewardTag: ["今日奖励", "本周奖励"],
        BtnFlush: "刷新",
        ServerShow: "所在服务器：{0}服",
        FlushWaiting: "请等待刷新时间结束",
        FlushLack: "{0}不足",
        MainChallenged: "该目标已被挑战",
        RecordShow: ["失败", "成功"],
        RecordType: ["防守", "挑战"],
        WeekEndTimer: "本周倒计时：<color=" + COLORSTR.Green4 + ">{0}</color>",
        ChallengeBtn: "挑战",
        ColdTips: "请等待冷却结束",
        score_desc: "跨服竞技场积分："
    },
    Territory: {
        MainName: "领 地",
        Title1: "领 地",
        Title2: "抢 夺",
        Title3: "领地日志",
        Level: "领地等级；{0}",
        BotNum: "未使用：{0}",
        BotFree: "已使用：{0}",
        CurRewardCount: "当前采集次数：{0}/{1}",
        StateDesc: "{0}状态",
        SpeedDesc: "(采集速度为{0}%)",
        BotState: ["兴奋", "正常", "疲劳", "脱力"],
        BotDesc: "当前采集状态：{0}状态，采集速度为{1}%",
        BotNum2: "树仆数量：{0}",
        Level2: "Lv.{0}",
        Limit: "上限{0}",
        UseNum: "{0}/{1}",
        UseNum2: `<color=#${COLORSTR.Red1}>{0}</color>/{1}`,
        ErrorText1: "超出上限",
        ErrorText2: "超出拥有数量",
        ErrorText3: "拥有宝箱数量过多，无法采集",
        ErrorText4: "当前暂无可用树仆",
        ErrorText5: "树仆正忙，请稍后再来",
        BotNum3: "树仆数量：{0}/{1}",
        FlushTime: "{0}后可刷新",
        NameList: ["我的领地", "他人领地"],
        BotDoing: "采集中",
        LockDesc: "{0}级解锁",
        DayDesc: "{0}天前",
        HourDesc: "{0}小时前",
        MinuDesc: "{0}分钟前",
        DateDesc: "{0}月{1}日",
        BuySucc: "购买成功",
        BuyLimit: "购买上限",
        BoxTip: "拥有宝箱数量过多，无法采集",
        NameList2: ["相邻领地", "仇人领地"],
        TitleList2: ["暂无对手", "暂无仇人"],
        MatchText: "趁你不在",
        BtnDesc: "复仇",
        Price: "¥{0}",
        Price2: "价值¥{0}",
        ActNoOpen: "活动未开启",
        refreshAd: "观看视频后，刷新所有资源"
    },
    MingXiang: {
        Box: "每日宝箱 <color=#" + COLORSTR.Green1 + ">{0}</color>/天",
        MaxTip: "今日快速领取次数已达上限",
        NoTip: "暂无可领取挂机奖励",
    },
    WeekLianChong: {
        OneDayNeedRecharge1: `单日充值\n满<color=#${COLORSTR.Green1}>{0}</color>元`,
        OneDayNeedRecharge2: `单日充值\n满<color=#${COLORSTR.Blue1}>{0}</color>元`,
        OneDayNeedRecharge3: `单日充值\n满<color=#${COLORSTR.Yellow9}>{0}</color>元`,
        DayDesc: "第{0}天",
        NeedRecharge: "充值{0}元可补领",
        TodatRecharge: `今日已累充：<color=#${COLORSTR.Yellow8}>{0}</color>元`,
        TimeStr5: `<color=#${COLORSTR.Green4}>{0}</color>天<color=#${COLORSTR.Green4}>{1}</color>时`,
    },
    FundAdv: {
        title: "双倍领取",
        LevelFundAdvTip: "完整观看广告后可双倍领取奖励"
    },
    LimitCoreDraw: {
        FreeLimitTime: "剩余{0}次",
    },
    CoreCrisis: {
        CoreName: ["", "坐骑之心", "法阵之心", "宝石之心", "星图之心", "铭文之心", "神器之心"],
        CoreLimitTips: "{0}等级不足",
        CoreLimitForGemTips: "{0}等级不足，无法继续镶嵌",
        MaxTip: "已达最大等级",
    },
    ItemRecycling: {
        Title: "回收神像",
        Title2: "供奉材料",
        ExpValue: `<color=#${COLORSTR.Yellow9}>{0}</color>/{1}`,
        ExpValue2: `<color=#${COLORSTR.Yellow9}>{0}</color><color=#${COLORSTR.Green4}>+{1}</color>/{2}`,
        MaxLevel: "已满级",
        NoSelect: "暂未选择任何物品",
    },
    PetGuard: {
        MainTitle: "宠物守护挑战",
        LayTitle: "第{0}层",
        ChallengeError: "请先完成上一层的挑战",
        AllChallengeComplete: "本层挑战已全部完成",
        BtnChallengeDone: "挑战完成",
        BtnChallengeStart: "开始挑战",
    },
    PetHuanHua: {
        Tip1: "缺少{0}",
        Tip2: "暂未开放",
        upTips: "升级成功",
        repTips: "替换成功",
        BtnTitle1: "已满级",
        BtnTitle2: "已选用",
        numTip0: `<color=#${COLORSTR.Red5}>{0}</color>/{1}`,
        numTip1: `<color=#${COLORSTR.Yellow2}>{0}</color>/{1}`,
    },
    ShenQiDuoBao: {
        TabTitle: ["神器奖励", "神器提升"],
        Tip1: "缺少{0}",
        TimeShow: ["天", "时", "分"],
        BtnGot: "已领取",
        BtnDoing: "未完成",
        BtnWait: "领取",
        LimitType: ["", "已购买", "每日限购次数", "限购次数"],
        Free: "免费",
        ValueShow: "价值:￥",
        ValueIconShow: "价值:",
        UnComplete: "任务未完成",
        RewardGot: "奖励已获得",
        LimitBuy: "限购次数已用完",
    },
    MerlinMagic: {
        Title: ["收藏室", "图鉴", "大书库"],
        Title2: ["按品质排列", "按主被动排列"],
        QuaDesc: ["优秀", "稀有", "史诗", "天赐", "神铸"],
    }
}

export let TextHelperWord: { [key: number]: string } = {
    [0]: "零",
    [1]: "一",
    [2]: "二",
    [3]: "三",
    [4]: "四",
    [5]: "五",
    [6]: "六",
    [7]: "七",
    [8]: "八",
    [9]: "九"
}
export let TextHelperUnits: { [key: number]: string } = {
    [1]: "十",
    [2]: "百",
    [3]: "千",
    [4]: "万",
}


export let AttrListIconName: { [key: number]: string } = {
    // [BATTLE_ATTR.ATTACK]: "attr_gongji",
    // [BATTLE_ATTR.ARMOR]: "attr_fangyu",
    // [BATTLE_ATTR.HP]: "attr_maxhp",
    // [BATTLE_ATTR.SPEED]: "attr_speed",
}

export let DateString: { [key: string]: string } = {
    ["day"]: "天",
    ["hour"]: "时",
    ["minute"]: "分",
    ["second"]: "秒",
}

export let AttrListName: { [key: number]: string } = {
    [BATTLE_ATTR.BATTLE_ATTR_MIN]: "任意",
    [BATTLE_ATTR.HP]: "生命",            // 生命 一般情况下， 生命值降为0时，战斗失败
    [BATTLE_ATTR.ATTACK]: "攻击",          // 攻击 提高造成的伤害
    [BATTLE_ATTR.ARMOR]: "防御",          // 防御 减少受到的伤害
    [BATTLE_ATTR.SPEED]: "速度",          // 速度 速度较高的玩家会在回合内先发起攻击
    [BATTLE_ATTR.TRUE_DAMAGE]: "最终伤害",      // 最终伤害 

    [BATTLE_ATTR.VAMPIRIC]: "吸血",        // 吸血//根据伤害，按吸血百分比回复自己生命//吸血量 = 造成的伤害 * （a吸血 - b忽视吸血）
    [BATTLE_ATTR.COUNTER]: "反击",        // 反击//反击 : 被攻击时有概率立即发起攻击，可打断对方连击，被击晕时无法反击//反击率 = a反击 - b忽视反击
    [BATTLE_ATTR.COMBO]: "连击",          // 连击//攻击时，有概率再次攻击，每次连击后概率都会衰减//连击率 = a连击 - b忽视连击
    [BATTLE_ATTR.EVASION]: "闪避",        // 闪避//有概率完全不受伤害
    [BATTLE_ATTR.CRITICAL]: "暴击",        // 暴击//攻击有概率攻击造成2倍伤害，暴击无法被闪避
    [BATTLE_ATTR.STUN]: "击晕",          // 击晕//攻击时有概率打晕对手，使其无法行动//击晕率 = a击晕 - b忽视击晕

    [BATTLE_ATTR.VAMPIRIC_IMMUNITY]: "忽视吸血",    // 忽视吸血//减少对方的吸血百分比
    [BATTLE_ATTR.COUNTER_IMMUNITY]: "忽视反击",    // 忽视反击//减少对方的反击几率
    [BATTLE_ATTR.COMBO_IMMUNITY]: "忽视连击",      // 忽视连击//减少对方的连击几率
    [BATTLE_ATTR.EVASION_IMMUNITY]: "忽视闪避",    // 忽视闪避//减少对方的闪避几率
    [BATTLE_ATTR.CRITICAL_IMMUNITY]: "忽视暴击",    // 忽视暴击//减少对方的暴击几率
    [BATTLE_ATTR.STUN_IMMUNITY]: "忽视击晕",      // 忽视击晕//减少对方的击晕几率

    [BATTLE_ATTR.TYRANNY]: "暴虐",        // 暴虐//暴击伤害倍率增加，10%即为暴击造成2.1倍伤害
    [BATTLE_ATTR.BENEVOLENCE]: "仁爱",      // 仁爱//仁爱 : 减少你受到暴击时的额外伤害，与对方的暴虐相互抵消
    [BATTLE_ATTR.MUDDY]: "泥泞",          // 泥泞//减少对方速度//战斗开始生效，使对方变为当前速度*（1 - 泥泞）
    [BATTLE_ATTR.INTERDICTION]: "禁疗",      // 禁疗//减少对方所有生命回复效果的百分比，到达100%时对方无法获得任何生命回复
    [BATTLE_ATTR.REJUVENATION]: "回复",      // 回复//第五回合时，按最大生命值百分比回复生命
    [BATTLE_ATTR.BULLYING]: "欺凌",        // 欺凌//对方生命低于50%时，造成额外伤害
    [BATTLE_ATTR.PILLAGE]: "掠财",        // 掠财//在竞技场获得更多金币
    [BATTLE_ATTR.GLADIATUS]: "角斗士",        // 角斗士//增加可携带挑战券数量
    [BATTLE_ATTR.MONEY_ADD]: "商人",
    [BATTLE_ATTR.HP_PER]: "生命百分比",
    [BATTLE_ATTR.ATTACK_PER]: "攻击百分比",
    [BATTLE_ATTR.ARMOR_PER]: "防御百分比",
    [BATTLE_ATTR.SPEED_PER]: "速度百分比",
    [BATTLE_ATTR.FISH_ATTR_1]: "矿物大小",
    [BATTLE_ATTR.FISH_ATTR_2]: "幸运",
    [BATTLE_ATTR.FISH_ATTR_3]: "强度",
    [BATTLE_ATTR.FISH_ATTR_4]: "防盗",
    [BATTLE_ATTR.FISH_ATTR_5]: "售卖价格",
}

export let AttrListDesc: { [key: number]: string } = {
    [BATTLE_ATTR.HP]: "增加生命",
    [BATTLE_ATTR.ATTACK]: "提高伤害",
    [BATTLE_ATTR.ARMOR]: "减少伤害",
    [BATTLE_ATTR.SPEED]: "提高出手速度",
    [BATTLE_ATTR.TRUE_DAMAGE]: "最终伤害",

    [BATTLE_ATTR.VAMPIRIC]: "伤害百分比回血",
    [BATTLE_ATTR.COUNTER]: "被攻击时反击",
    [BATTLE_ATTR.COMBO]: "再次发动攻击",
    [BATTLE_ATTR.EVASION]: "闪避对方攻击",
    [BATTLE_ATTR.CRITICAL]: "造成两倍伤害",
    [BATTLE_ATTR.STUN]: "使对方眩晕",

    [BATTLE_ATTR.VAMPIRIC_IMMUNITY]: "减少对方吸血",
    [BATTLE_ATTR.COUNTER_IMMUNITY]: "减少对方反击",
    [BATTLE_ATTR.COMBO_IMMUNITY]: "减少对方连击",
    [BATTLE_ATTR.EVASION_IMMUNITY]: "减少对方闪避",
    [BATTLE_ATTR.CRITICAL_IMMUNITY]: "减少对方暴击",
    [BATTLE_ATTR.STUN_IMMUNITY]: "减少对方击晕",

    [BATTLE_ATTR.TYRANNY]: "提高暴击伤害",
    [BATTLE_ATTR.BENEVOLENCE]: "减少对方暴击伤害",
    [BATTLE_ATTR.MUDDY]: "减少对方速度",
    [BATTLE_ATTR.INTERDICTION]: "减少对方生命回复",
    [BATTLE_ATTR.REJUVENATION]: "第五回合时，按最大生命值百分比回复生命",
    [BATTLE_ATTR.BULLYING]: "生命越低伤害越高",
    [BATTLE_ATTR.PILLAGE]: "竞技场金币增加",
    [BATTLE_ATTR.GLADIATUS]: "挑战卷携带数+1",
    [BATTLE_ATTR.MONEY_ADD]: "装备出售获得金钱增加",

}

export let EquipQuality: { [key: number]: string } = {
    [1]: "【普通的】",
    [2]: "【优秀的】",
    [3]: "【精良的】",
    [4]: "【稀有的】",
    [5]: "【史诗的】",
    [6]: "【传奇的】",
    [7]: "【天赐的】",
    [8]: "【神铸的】",
}
export let EquipName: { [key: number]: string } = {
    [EQUIP_TYPE.ER_HUAN]: "耳环",
    [EQUIP_TYPE.XIANG_LIAN]: "项链",
    [EQUIP_TYPE.TOU_KUI]: "头盔",
    [EQUIP_TYPE.HU_WAN]: "护腕",
    [EQUIP_TYPE.JIAN_BANG]: "魔法书",
    [EQUIP_TYPE.KAI_JIA]: "铠甲",
    [EQUIP_TYPE.YAO_DAI]: "腰带",
    [EQUIP_TYPE.JIE_ZHI]: "戒指",
    [EQUIP_TYPE.WU_QI]: "武器",
    [EQUIP_TYPE.KU_ZI]: "手镯",
    [EQUIP_TYPE.XIE_ZI]: "鞋子",
    [EQUIP_TYPE.DUN_PAI]: "盾牌",
}
