import { JsonAsset } from "cc";
import { _CreateCfgActivity } from "config/CfgActivity";
import { _CreateCfgActivityOpen } from "config/CfgActivityOpen";
import { _CreateCfgAngel } from "config/CfgAngel";
import { _CreateCfgArena } from "config/CfgArena";
import { _CreateCfgBox } from "config/CfgBox";
import { _CreateCfgBoxFund } from "config/CfgBoxFund";
import { _CreateCfgBoxManor } from "config/CfgBoxManor";
import { _CreateCfgCaveLoot } from "config/CfgCaveLoot";
import { _CreateCfgCommodityGuild } from "config/CfgCommodityGuild";
import { _CreateCfgDundries } from "config/CfgDundries";
import { _CreateCfgDuoBao } from "config/CfgDuobao";
import { _CreateCfgEquip } from "config/CfgEquip";
import { _CreateCfgEquipAngle } from "config/CfgEquipmentAngle";
import { _CreateCfgEquipShiLian } from "config/CfgEquipmentShiLian";
import { _CreateError } from "config/CfgError";
import { _CreateCfgEscortData } from "config/CfgEscort";
import { _CreateCfgFashion } from "config/CfgFashion";
import { _CreateCfgFirstCharge } from "config/CfgFirstCharge";
import { _CreateCfgGem } from "config/CfgGem";
import { _CreateCfgGemCfg } from "config/CfgGemCfg";
import { _CreateCfgGemDraw } from "config/CfgGemDraw";
import { _CreateCfgGift } from "config/CfgGift";
import { _CreateCfgGuideData } from "config/CfgGuide";
import { _CreateCfgGuMoChengJiu } from "config/CfgGuMoChengJiu";
import { _CreateCfgGuMoPagoda } from "config/CfgGuMoPagoda";
import { _CreateCfgInviteFriend } from "config/CfgInvityFriend";
import { _CreateCfgKnights } from "config/CfgKnights";
import { _CreateCfgLanguage } from "config/CfgLanguage";
import { _CreateCfgLeiChong } from "config/CfgLeiChong";
import { _CreateCfgLevelFund } from "config/CfgLevelFund";
import { _CreateCfgLingZhu } from "config/CfgLingZhu";
import { _CreateCfgMaoXian } from "config/CfgMaoxian";
import { _CreateCfgMonster } from "config/CfgMonster";
import { _CreateCfgMonsterGroup } from "config/CfgMonsterGroup";
import { _CreateCfgMount } from "config/CfgMount";
import { _CreateCfgNeoServer } from "config/CfgNeoServer";
import { _CreateCfgNeoShop } from "config/CfgNeoShop";
import { _CreateCfgOrb } from "config/CfgOrb";
import { _CreateCfgOther } from "config/CfgOther";
import { _CreateCfgPet } from "config/CfgPet";
import { _CreateCfgRecharge } from "config/CfgRecharge";
import { _CreateCfgRoleExp } from "config/CfgRoleExp";
import { _CreateCfgScore } from "config/CfgScore";
import { _CreateCfgSevenDays } from "config/CfgSevenDay";
import { _CreateCfgServerBoxOpen } from "config/CfgSeverBoxOpen";
import { _CreateCfgShenMi } from "config/CfgShenMi";
import { _CreateCfgShiLianPagoda } from "config/CfgShiLianPagoda";
import { _CreateCfgShop } from "config/CfgShop";
import { _CreateCfgStarMap } from "config/CfgStarmap";
import { _CreateCfgTask } from "config/CfgTask";
import { _CreateCfgTitleCfg } from "config/CfgTitleCfg";
import { _CreateCfgTitleItem } from "config/CfgTitleItem";
import { _CreateCfgWaBao } from "config/CfgWaBao";
import { _CreateCfgWeekendRecharge } from "config/CfgWeekendRecharge";
import { Singleton } from "core/Singleton";

import { _CreateCfgAd } from "config/CfgAd";
import { _CreateCfgAngelFes } from "config/CfgAngelFes";
import { _CreateCfgBlock } from "config/CfgBlock";
import { _CreateCfgBlockItem } from "config/CfgBlockItem";
import { _CreateCfgBlockModelItem } from "config/CfgBlockModelItem";
import { _CreateCfgChaoZhiXianLi } from "config/CfgChaoZhiXianLi";
import { _CreateCfgDailyGift } from "config/CfgDailyGift";
import { _CreateCfgDebris } from "config/CfgDebris";
import { _CreateCfgDFArena } from "config/CfgDFArena";
import { _CreateCfgEnchant } from "config/CfgEnchant";
import { _CfgExclusiveGiftBag } from "config/CfgExclusiveGiftBag";
import { _CreateCfgFunOpen } from "config/CfgFunOpen";
import { _CreateCfgGetWay } from "config/CfgGetWay";
import { _CreateCfgGuild } from "config/CfgGuild";
import { _CreateCfgHarness } from "config/CfgHarness";
import { _CreateCfgInscription } from "config/CfgInscription";
import { _CreateCfgInscriptionChengJiu } from "config/CfgInscriptionChengJiu";
import { _CreateCfgInscriptionItem } from "config/CfgInscriptionItem";
import { _CreateCfgInscriptionTower } from "config/CfgInscriptionTower";
import { _CfgIntegralTurntable } from "config/CfgIntegralTurntable";
import { _CreateCfgItemRetrieve } from "config/CfgItemRetrieve";
import { _CreateCfgJinRiFenXiang } from "config/CfgJinRiFenXiang";
import { _CreateCfgKnightCard } from "config/CfgKnightCard";
import { _CreateCfgLianChongZengLi } from "config/CfgLianChongZengLi";
import { _CreateCfgLimitCore } from "config/CfgLimitCore";
import { _CreateCfgLuckyGift } from "config/CfgLuckyGift";
import { _CreateCfgMerlinMagic } from "config/CfgMerlinMagic";
import { _CreateCfgMonthlyCard } from "config/CfgMonthlyCard";
import { _CreateCfgPassiveSkill } from "config/CfgPassiveSkill";
import { _CreateCfgSingleSkill } from "config/CfgSingleSkill";
import { _CreateCfgPetClothData } from "config/CfgPetCloth";
import { _CreateCfgPetClothFB } from "config/CfgPetClothFB";
import { _CreateCfgPetItem } from "config/CfgPetItem";
import { _CreateCfgScoreFund } from "config/CfgScoreFund";
import { _CreateCfgScrollItem } from "config/CfgScrollItem";
import { _CreateCfgSensitivewords } from "config/CfgSensitivewords";
import { _CreateCfgShenQi } from "config/CfgShenQi";
import { _CreateCfgShenQiDuoBao } from "config/CfgShenQiDuoBao";
import { _CreateCfgShouChongDingZhiData } from "config/CfgShouChongDingZhi";
import { _CreateCfgStarMapFes } from "config/CfgStarMapFes";
import { _CreateCfgTerritory } from "config/CfgTerritory";
import { _CreateCfgTerritoryGift } from "config/CfgTerritoryGift";
import { _CreateCfgTianXuanZhiLiData } from "config/CfgTianXuanZhiLi";
import { _CreateCfgWarOrder } from "config/CfgWarOrder";
import { _CreateCfgWeekHaoLi } from "config/CfgWeekHaoLi";
import { _CreateCfgWeekLianChong } from "config/CfgWeekLianChong";
import { _CreateCfgXinFuBiPin } from "config/CfgXinFuBiPin";
import { ReportManager, ReportType } from "../proload/ReportManager";
import { _CfgClothShop } from "config/CfgClothShop";
import { PreloadToolFuncs, Report2Type } from "preload/PreloadToolFuncs";
export class CfgManager extends Singleton {
    // private _data  : {[index:string] : CfgDataBase ;};
    private needLoadCount: number = 0;
    private loadedCount: number = 0;
    // private 
    public Init() {
        PreloadToolFuncs.report2(Report2Type.ID_12, Report2Type.ID_10060, Report2Type.par_12());
        this.createCfg(_CreateError);
        this.createCfg(_CreateCfgSensitivewords);
        this.createCfg(_CreateCfgFunOpen)
        this.createCfg(_CreateCfgBox);
        this.createCfg(_CreateCfgMaoXian);
        this.createCfg(_CreateCfgDundries);
        this.createCfg(_CreateCfgEquip);
        this.createCfg(_CreateCfgShop);
        this.createCfg(_CreateCfgOther);
        this.createCfg(_CreateCfgGift);
        this.createCfg(_CreateCfgWaBao);
        this.createCfg(_CreateCfgBlockModelItem);
        this.createCfg(_CreateCfgBlockItem);
        this.createCfg(_CreateCfgKnights);
        this.createCfg(_CreateCfgLingZhu);
        this.createCfg(_CreateCfgRoleExp);
        this.createCfg(_CreateCfgTitleItem);
        this.createCfg(_CreateCfgTitleCfg);
        this.createCfg(_CreateCfgShenMi);
        this.createCfg(_CreateCfgAngel);
        this.createCfg(_CreateCfgEquipAngle);
        this.createCfg(_CreateCfgScore);
        this.createCfg(_CreateCfgMount);
        this.createCfg(_CreateCfgLanguage);
        this.createCfg(_CreateCfgShiLianPagoda);
        this.createCfg(_CreateCfgGuMoPagoda);
        this.createCfg(_CreateCfgGuild);
        this.createCfg(_CreateCfgOrb);
        this.createCfg(_CreateCfgShenQi);
        this.createCfg(_CreateCfgInscriptionTower);
        this.createCfg(_CreateCfgBlock);
        this.createCfg(_CfgExclusiveGiftBag);
        this.createCfg(_CreateCfgEquipShiLian);
        this.createCfg(_CreateCfgXinFuBiPin);
        this.createCfg(_CreateCfgKnightCard);
        this.createCfg(_CreateCfgTask);
        this.createCfg(_CreateCfgMonsterGroup);
        this.createCfg(_CreateCfgMonster);
        this.createCfg(_CfgClothShop);
        this.createCfg(_CreateCfgArena);
        this.createCfg(_CreateCfgGuideData);
        this.createCfg(_CreateCfgStarMap);
        this.createCfg(_CreateCfgPet);
        this.createCfg(_CreateCfgEscortData);
        this.createCfg(_CreateCfgActivity);
        this.createCfg(_CreateCfgActivityOpen);
        this.createCfg(_CreateCfgRecharge);
        this.createCfg(_CreateCfgBoxFund);
        this.createCfg(_CreateCfgCommodityGuild);
        this.createCfg(_CreateCfgGem);
        this.createCfg(_CreateCfgGemDraw);
        this.createCfg(_CreateCfgGemCfg);
        this.createCfg(_CreateCfgLevelFund);
        this.createCfg(_CreateCfgGuMoChengJiu);
        this.createCfg(_CreateCfgDuoBao);
        this.createCfg(_CreateCfgCaveLoot);
        this.createCfg(_CreateCfgWeekendRecharge);
        this.createCfg(_CreateCfgWeekHaoLi);
        this.createCfg(_CreateCfgInviteFriend);
        this.createCfg(_CreateCfgFirstCharge);
        this.createCfg(_CreateCfgBoxManor);
        this.createCfg(_CreateCfgFashion);
        this.createCfg(_CreateCfgSevenDays);
        this.createCfg(_CreateCfgServerBoxOpen);
        this.createCfg(_CreateCfgNeoServer);
        this.createCfg(_CreateCfgNeoShop);
        this.createCfg(_CreateCfgLeiChong);
        this.createCfg(_CreateCfgDebris);
        this.createCfg(_CreateCfgLuckyGift);
        this.createCfg(_CreateCfgDailyGift);
        this.createCfg(_CreateCfgMonthlyCard);
        this.createCfg(_CreateCfgGetWay);
        this.createCfg(_CreateCfgPassiveSkill);
        this.createCfg(_CreateCfgSingleSkill);
        this.createCfg(_CreateCfgPetItem);
        this.createCfg(_CreateCfgJinRiFenXiang);
        this.createCfg(_CreateCfgScoreFund);
        this.createCfg(_CreateCfgInscription);
        this.createCfg(_CreateCfgInscriptionItem);
        this.createCfg(_CreateCfgAngelFes);
        this.createCfg(_CreateCfgAd);
        this.createCfg(_CreateCfgStarMapFes);
        this.createCfg(_CreateCfgChaoZhiXianLi);
        this.createCfg(_CreateCfgInscriptionChengJiu);
        this.createCfg(_CreateCfgLianChongZengLi);
        this.createCfg(_CreateCfgWeekLianChong);
        this.createCfg(_CreateCfgEnchant);
        this.createCfg(_CreateCfgTerritory);
        this.createCfg(_CreateCfgWarOrder);
        this.createCfg(_CreateCfgDFArena);
        this.createCfg(_CreateCfgLimitCore);
        this.createCfg(_CreateCfgItemRetrieve);
        this.createCfg(_CreateCfgPetClothData);
        this.createCfg(_CfgIntegralTurntable);
        this.createCfg(_CreateCfgPetClothFB);
        this.createCfg(_CreateCfgShenQiDuoBao);
        this.createCfg(_CreateCfgHarness);
        this.createCfg(_CreateCfgTianXuanZhiLiData);
        this.createCfg(_CreateCfgTerritoryGift);
        this.createCfg(_CreateCfgShouChongDingZhiData);
        this.createCfg(_CreateCfgScrollItem);
        this.createCfg(_CreateCfgMerlinMagic);
    }

    createCfg(func: (onCom: (suc: boolean) => void) => void) {
        ++this.needLoadCount
        func((suc) => {
            if (suc) { ++this.loadedCount; }
            if (this.loadedCount == this.needLoadCount) {
                PreloadToolFuncs.report2(Report2Type.ID_12, Report2Type.ID_10070, Report2Type.par_12());
                ReportManager.Inst().sendPoint(ReportType.endLoadConfig);
                this.cb && this.cb() && (this.cb = undefined);
            }
        })
    }
    private cb: Function;
    public IsLoadComplete(cb?: Function) {
        if (this.loadedCount != this.needLoadCount)
            this.cb = cb;
        return this.loadedCount == this.needLoadCount;
    }
    public static JsonGetKeyCfg(jsonAss: JsonAsset, table_name: string) {
        return (<{ [key: string]: any }>jsonAss.json)[table_name];
    }
}